* revamped build system for a cleaner support of both Xenomai 2.1 and   the pervious RTAI and Xenomai versions
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@917 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -19864,7 +19864,7 @@ if test "${with_rtext+set}" = set; then
 echo "$as_me: error: You must supply an argument to --with-rtext." >&2;}
    { (exit 1); exit 1; }; } ;;
         *)
-            CONFIG_RTEXT_DIR=${withval} ;;
+            CONFIG_RTNET_RTEXT_DIR=${withval} ;;
     esac
 fi;
 
@@ -19885,26 +19885,72 @@ fi;
 
 
 
-echo "$as_me:$LINENO: checking for RT-extension installation" >&5
-echo $ECHO_N "checking for RT-extension installation... $ECHO_C" >&6
-RTAI_CONFIG="${CONFIG_RTEXT_DIR}/bin/rtai-config"
-if test -x "${RTAI_CONFIG}"; then
-    RTAI_DIR="`cd ${CONFIG_RTEXT_DIR} && pwd`"   # let the shell normalize the path
-    XENO_DIR=
-    echo "$as_me:$LINENO: result: ${RTAI_DIR} (RTAI)" >&5
+echo "$as_me:$LINENO: checking for RT-extension" >&5
+echo $ECHO_N "checking for RT-extension... $ECHO_C" >&6
+
+if test "${CONFIG_RTNET_RTEXT_CLASSIC}" = "y"; then
+    RTAI_CONFIG="${CONFIG_RTNET_RTEXT_DIR}/bin/rtai-config"
+    if test -x "${RTAI_CONFIG}"; then
+        RTAI_DIR="`cd ${CONFIG_RTNET_RTEXT_DIR} && pwd`"   # let the shell normalize the path
+        XENO_DIR=""
+        echo "$as_me:$LINENO: result: ${RTAI_DIR} (RTAI)" >&5
 echo "${ECHO_T}${RTAI_DIR} (RTAI)" >&6
-else
-    XENO_CONFIG="${CONFIG_RTEXT_DIR}/bin/xeno-config"
-    if test -x "${XENO_CONFIG}"; then
-        RTAI_DIR=
-        XENO_DIR="`cd ${CONFIG_RTEXT_DIR} && pwd`"   # let the shell normalize the path
-        echo "$as_me:$LINENO: result: ${XENO_DIR} (Xenomai)" >&5
-echo "${ECHO_T}${XENO_DIR} (Xenomai)" >&6
     else
-        { { echo "$as_me:$LINENO: error: *** No RT-extension found in $CONFIG_RTEXT_DIR" >&5
-echo "$as_me: error: *** No RT-extension found in $CONFIG_RTEXT_DIR" >&2;}
+        XENO_CONFIG="${CONFIG_RTNET_RTEXT_DIR}/bin/xeno-config"
+        if test -x "${XENO_CONFIG}"; then
+            RTAI_DIR=""
+            XENO_DIR="`cd ${CONFIG_RTNET_RTEXT_DIR} && pwd`"   # let the shell normalize the path
+            echo "$as_me:$LINENO: result: ${XENO_DIR} (Xenomai 2.0.x)" >&5
+echo "${ECHO_T}${XENO_DIR} (Xenomai 2.0.x)" >&6
+        else
+            { { echo "$as_me:$LINENO: error: *** No RT-extension found in $CONFIG_RTNET_RTEXT_DIR" >&5
+echo "$as_me: error: *** No RT-extension found in $CONFIG_RTNET_RTEXT_DIR" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+else
+    RTAI_DIR=""
+    XENO_DIR=""
+
+
+# Check whether --with-linux or --without-linux was given.
+if test "${with_linux+set}" = set; then
+  withval="$with_linux"
+  case "${withval}" in
+            "" | y | ye | yes | n | no)
+                { { echo "$as_me:$LINENO: error: You must supply an argument to --with-linux." >&5
+echo "$as_me: error: You must supply an argument to --with-linux." >&2;}
+   { (exit 1); exit 1; }; } ;;
+            *)
+                CONFIG_RTNET_LINUX_DIR=${withval} ;;
+        esac
+fi;
+
+    # get linux kernel tree and version
+    RTEXT_LINUX_DIR="${CONFIG_RTNET_LINUX_DIR}"
+    RTEXT_LINUX_VERSION=`grep "#define UTS_RELEASE" $RTEXT_LINUX_DIR/include/linux/version.h | sed -e 's/[^\"]*\"\([^\"]*\)\"/\1/'`
+
+    if test \! -f ${RTEXT_LINUX_DIR}/include/xenomai/nucleus/version.h; then
+        { { echo "$as_me:$LINENO: error: *** RT-extended kernel not found in $RTEXT_LINUX_DIR" >&5
+echo "$as_me: error: *** RT-extended kernel not found in $RTEXT_LINUX_DIR" >&2;}
    { (exit 1); exit 1; }; }
     fi
+
+    XENO_CONFIG=${CONFIG_RTNET_RTEXT_CONFIG_PATH}
+    if test "${XENO_CONFIG}" = ""; then
+        XENO_CONFIG=`which xeno-config 2>/dev/null`
+        if test "${XENO_CONFIG}" = "" && test "${CONFIG_RTNET_EXAMPLES}" \!= "y"; then
+            XENO_CONFIG="/bin/true"
+        fi
+    fi
+    if test "${XENO_CONFIG}" = "" || test \! -x ${XENO_CONFIG}; then
+        { { echo "$as_me:$LINENO: error: *** Xenomai configuration tool not found: ${XENO_CONFIG}" >&5
+echo "$as_me: error: *** Xenomai configuration tool not found: ${XENO_CONFIG}" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+    echo "$as_me:$LINENO: result: $RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP} + Xenomai)" >&5
+echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP} + Xenomai)" >&6
 fi
 
 #
@@ -19912,32 +19958,10 @@ fi
 # it will be fatal, thus exit with AC_MSG_ERROR
 #
 
+XENO_VERSION=""
+RTAI_VERSION=""
+
 if test "$RTAI_DIR" \!= ""; then
-    #
-    # check if RTAI is installed with DESTDIR
-    # e.g.: 'make DESTDIR=/foo install'
-    #
-    echo "$as_me:$LINENO: checking for RTAI DESTDIR" >&5
-echo $ECHO_N "checking for RTAI DESTDIR... $ECHO_C" >&6
-    RTNET_RTEXT_PREFIX="`cd \`${RTAI_CONFIG} --prefix\` && pwd`"        # let the shell normalize the path
-    if test "${RTNET_RTEXT_PREFIX}" \!= "${RTAI_DIR}"; then
-        RTAI_DESTDIR="`cd \`echo ${RTAI_DIR} | sed -e s,${RTNET_RTEXT_PREFIX}$,,\` && pwd`"
-        export DESTDIR="${RTAI_DESTDIR}"
-
-        RTNET_RTEXT_PREFIX="`cd \`${RTAI_CONFIG} --prefix\` && pwd`"    # let the shell normalize the path
-        if test "${RTNET_RTEXT_PREFIX}" = "${RTAI_DIR}"; then
-            echo "$as_me:$LINENO: result: ${DESTDIR}" >&5
-echo "${ECHO_T}${DESTDIR}" >&6
-        else
-            { { echo "$as_me:$LINENO: error: *** Cannot identify DESTDIR" >&5
-echo "$as_me: error: *** Cannot identify DESTDIR" >&2;}
-   { (exit 1); exit 1; }; }
-        fi
-    else
-        echo "$as_me:$LINENO: result: none" >&5
-echo "${ECHO_T}none" >&6
-    fi
-
     echo "$as_me:$LINENO: checking for RTAI version" >&5
 echo $ECHO_N "checking for RTAI version... $ECHO_C" >&6
     RTAI_VERSION="`${RTAI_CONFIG} --version`"
@@ -19982,33 +20006,10 @@ echo "${ECHO_T}${RTAI_CONFIG_FILE}" >&6
 echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
     RTEXT_LINUX_DIR="`${RTAI_CONFIG} --linux-dir`"
     RTEXT_LINUX_VERSION="`${RTAI_CONFIG} --linux-version`"
+    echo "$as_me:$LINENO: result: $RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&5
+echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&6
 
 elif test "$XENO_DIR" \!= ""; then
-    #
-    # check if Xenomai is installed with DESTDIR
-    # e.g.: 'make DESTDIR=/foo install'
-    #
-    echo "$as_me:$LINENO: checking for Xenomai DESTDIR" >&5
-echo $ECHO_N "checking for Xenomai DESTDIR... $ECHO_C" >&6
-    RTNET_RTEXT_PREFIX="`cd \`${XENO_CONFIG} --prefix\` && pwd`"        # let the shell normalize the path
-    if test "${RTNET_RTEXT_PREFIX}" \!= "${XENO_DIR}"; then
-        XENO_DESTDIR="`cd \`echo ${XENO_DIR} | sed -e s,${RTNET_RTEXT_PREFIX}$,,\` && pwd`"
-        export DESTDIR="${XENO_DESTDIR}"
-
-        RTNET_RTEXT_PREFIX="`cd \`${XENO_CONFIG} --prefix\` && pwd`"    # let the shell normalize the path
-        if test "${RTNET_RTEXT_PREFIX}" = "${XENO_DIR}"; then
-            echo "$as_me:$LINENO: result: ${DESTDIR}" >&5
-echo "${ECHO_T}${DESTDIR}" >&6
-        else
-            { { echo "$as_me:$LINENO: error: *** Cannot identify DESTDIR" >&5
-echo "$as_me: error: *** Cannot identify DESTDIR" >&2;}
-   { (exit 1); exit 1; }; }
-        fi
-    else
-        echo "$as_me:$LINENO: result: none" >&5
-echo "${ECHO_T}none" >&6
-    fi
-
     echo "$as_me:$LINENO: checking for Xenomai version" >&5
 echo $ECHO_N "checking for Xenomai version... $ECHO_C" >&6
     XENO_VERSION="`${XENO_CONFIG} --version`"
@@ -20023,28 +20024,42 @@ _ACEOF
 
             echo "$as_me:$LINENO: result: ${XENO_VERSION}" >&5
 echo "${ECHO_T}${XENO_VERSION}" >&6
+            ;;
+        *)
+            { { echo "$as_me:$LINENO: error: *** Unsupported Xenomai version $XENO_VERSION in $XENO_DIR" >&5
+echo "$as_me: error: *** Unsupported Xenomai version $XENO_VERSION in $XENO_DIR" >&2;}
+   { (exit 1); exit 1; }; }
+            ;;
+    esac
 
-            echo "$as_me:$LINENO: checking for Xenomai config file" >&5
+    echo "$as_me:$LINENO: checking for Xenomai config file" >&5
 echo $ECHO_N "checking for Xenomai config file... $ECHO_C" >&6
-            XENO_CONFIG_FILE="`${XENO_CONFIG} --config`"
-            if test \! -f $XENO_CONFIG_FILE; then
-                { { echo "$as_me:$LINENO: error: *** Xenomai configuration file not found" >&5
+    XENO_CONFIG_FILE="`${XENO_CONFIG} --config`"
+    if test \! -f $XENO_CONFIG_FILE; then
+        { { echo "$as_me:$LINENO: error: *** Xenomai configuration file not found" >&5
 echo "$as_me: error: *** Xenomai configuration file not found" >&2;}
    { (exit 1); exit 1; }; }
-            fi
-            echo "$as_me:$LINENO: result: ${XENO_CONFIG_FILE}" >&5
+    fi
+    echo "$as_me:$LINENO: result: ${XENO_CONFIG_FILE}" >&5
 echo "${ECHO_T}${XENO_CONFIG_FILE}" >&6
 
-            # source (load) the Xenomai configuration
-            . ${XENO_CONFIG_FILE}
+    # source (load) the Xenomai configuration
+    . ${XENO_CONFIG_FILE}
 
-            # get linux kernel tree and version
-            echo "$as_me:$LINENO: checking for Linux source tree" >&5
+    # get linux kernel tree and version
+    echo "$as_me:$LINENO: checking for Linux source tree" >&5
 echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
-            RTEXT_LINUX_DIR="`${XENO_CONFIG} --linux-dir`"
-            RTEXT_LINUX_VERSION="`${XENO_CONFIG} --linux-version`"
+    RTEXT_LINUX_DIR="`${XENO_CONFIG} --linux-dir`"
+    RTEXT_LINUX_VERSION="`${XENO_CONFIG} --linux-version`"
+    echo "$as_me:$LINENO: result: $RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&5
+echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&6
 
-            ;;
+else
+    echo "$as_me:$LINENO: checking for Xenomai version" >&5
+echo $ECHO_N "checking for Xenomai version... $ECHO_C" >&6
+    XENO_VERSION=`grep "#define XENO_VERSION_STRING" $RTEXT_LINUX_DIR/include/xenomai/nucleus/version.h | sed -e 's/[^\"]*\"\([^\"]*\)\"/\1/'`
+
+    case "$XENO_VERSION" in
         2.1*)
             CONFIG_RTNET_RTEXT_VERSION=xeno-21x
 
@@ -20054,54 +20069,22 @@ _ACEOF
 
             echo "$as_me:$LINENO: result: ${XENO_VERSION}" >&5
 echo "${ECHO_T}${XENO_VERSION}" >&6
-
-
-# Check whether --with-linux or --without-linux was given.
-if test "${with_linux+set}" = set; then
-  withval="$with_linux"
-  case "${withval}" in
-                    "" | y | ye | yes | n | no)
-                        { { echo "$as_me:$LINENO: error: You must supply an argument to --with-linux." >&5
-echo "$as_me: error: You must supply an argument to --with-linux." >&2;}
-   { (exit 1); exit 1; }; } ;;
-                    *)
-                        CONFIG_RTNET_LINUX_DIR=${withval} ;;
-                esac
-fi;
-
-            # get linux kernel tree and version
-            echo "$as_me:$LINENO: checking for Linux source tree" >&5
-echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
-            RTEXT_LINUX_DIR="${CONFIG_RTNET_LINUX_DIR}"
-            eval linux_`grep '^EXTRAVERSION =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
-            eval linux_`grep '^PATCHLEVEL =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
-            eval linux_`grep '^SUBLEVEL =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
-            eval linux_`grep '^VERSION =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
-            RTEXT_LINUX_VERSION="$linux_VERSION.$linux_PATCHLEVEL.$linux_SUBLEVEL$linux_EXTRAVERSION"
-
             ;;
         *)
-            { { echo "$as_me:$LINENO: error: *** Unsupported Xenomai version $XENO_VERSION in $XENO_DIR" >&5
-echo "$as_me: error: *** Unsupported Xenomai version $XENO_VERSION in $XENO_DIR" >&2;}
+            { { echo "$as_me:$LINENO: error: *** Unsupported Xenomai version $XENO_VERSION in $RTEXT_LINUX_DIR" >&5
+echo "$as_me: error: *** Unsupported Xenomai version $XENO_VERSION in $RTEXT_LINUX_DIR" >&2;}
    { (exit 1); exit 1; }; }
             ;;
     esac
 
-else
-    { { echo "$as_me:$LINENO: error: *** internal error" >&5
-echo "$as_me: error: *** internal error" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 
 #source (load) the kernel configuration
 . ${RTEXT_LINUX_DIR}/.config
 
-echo "$as_me:$LINENO: result: $RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&5
-echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&6
 
 
-
-if test "$RTAI_DIR" \!= ""; then
+if test "$RTAI_VERSION" \!= ""; then
   CONFIG_RTAI_TRUE=
   CONFIG_RTAI_FALSE='#'
 else
@@ -20111,7 +20094,7 @@ fi
 
 
 
-if test "$XENO_DIR" \!= ""; then
+if test "$XENO_VERSION" \!= ""; then
   CONFIG_XENO_TRUE=
   CONFIG_XENO_FALSE='#'
 else
@@ -20267,8 +20250,12 @@ case "${CONFIG_RTNET_RTEXT_VERSION}" in
         ;;
     xeno-21x)
         RTEXT_USER_CFLAGS="`${XENO_CONFIG} --xeno-cflags`"
-        CONFIG_RTNET_RTEXT_ARCH="`${XENO_CONFIG} --arch`"
         RTEXT_LIBRARIES="`${XENO_CONFIG} --library-dir`"
+        if test "`eval echo \\$$wanted_kernel_arch`" \!= ""; then
+            CONFIG_RTNET_RTEXT_ARCH="${RTNET_TARGET_ARCH}"
+        else
+            CONFIG_RTNET_RTEXT_ARCH="<something else>"
+        fi
         ;;
     *)
         { { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -20287,7 +20274,7 @@ if test "$CONFIG_KBUILD" = "y"; then
             RTEXT_KMOD_CFLAGS="`${XENO_CONFIG} --module-cflags`"
             ;;
         xeno-21x)
-            RTEXT_KMOD_CFLAGS="-I ${RTEXT_LINUX_DIR}/include/xenomai"
+            RTEXT_KMOD_CFLAGS="-I${RTEXT_LINUX_DIR}/include/xenomai"
             ;;
         *)
             { { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -20417,8 +20404,7 @@ else
                 ARCH=\$(RTNET_TARGET_ARCH)                                  \
                 M=\"\`pwd\`\"                                               \
                 V=\$(V)                                                     \
-                rtfw_dir=\"${RTNET_RTFW_PREFIX}\"                           \
-                rtext_dir=\"${RTNET_RTEXT_PREFIX}\"                         \
+                rtext_kmod_cflags=\"\$(RTEXT_KMOD_CFLAGS)\"                 \
                 top_srcdir=\"\`cd \$(top_srcdir) && pwd\`\"                 \
                 top_builddir=\"\`cd \$(top_builddir) && pwd\`\"             \
                 srcdir=\"\`cd \$(srcdir) && pwd\`\"                         \
@@ -20537,8 +20523,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: *** header not found or working, please check RTAI installation" >&5
-echo "$as_me: error: *** header not found or working, please check RTAI installation" >&2;}
+  { { echo "$as_me:$LINENO: error: *** header not found or working, please check RT-extension installation" >&5
+echo "$as_me: error: *** header not found or working, please check RT-extension installation" >&2;}
    { (exit 1); exit 1; }; }
 fi
 done
@@ -20679,8 +20665,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: *** header not found or working, please check RTAI installation" >&5
-echo "$as_me: error: *** header not found or working, please check RTAI installation" >&2;}
+  { { echo "$as_me:$LINENO: error: *** header not found or working, please check RT-extension installation" >&5
+echo "$as_me: error: *** header not found or working, please check RT-extension installation" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -21646,7 +21632,6 @@ fi
 
 
 RTEXT_KMOD_CFLAGS="-D__IN_RTNET__ $RTEXT_KMOD_CFLAGS"
-RTEXT_USER_CFLAGS="-D__IN_RTNET__ $RTEXT_USER_CFLAGS"
 
 
 
