* new RT-NIC selection scheme (rt_eepro100 patch by Fabian Koch,   extended to other drivers) * added support for fusion 0.7.2 * RTDM userspace support for fusion * added fusion examples
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@773 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LD CONFIG_NCURSES_TRUE CONFIG_NCURSES_FALSE NCURSES_LIBS LIBOBJS CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE RTNET_TARGET_ARCH CROSS_COMPILE RTNET_MODULE_EXT RTNET_KBUILD_ENV RTNET_KBUILD_CMD RTNET_KBUILD_CLEAN RTNET_MODULE_DIR CONFIG_NEWLXRT_TRUE CONFIG_NEWLXRT_FALSE CONFIG_RTNET_3C59X_TRUE CONFIG_RTNET_3C59X_FALSE CONFIG_RTNET_8139_TRUE CONFIG_RTNET_8139_FALSE CONFIG_RTNET_EEPRO100_TRUE CONFIG_RTNET_EEPRO100_FALSE CONFIG_RTNET_PCNET32_TRUE CONFIG_RTNET_PCNET32_FALSE CONFIG_RTNET_VIA_RHINE_TRUE CONFIG_RTNET_VIA_RHINE_FALSE CONFIG_RTNET_NATSEMI_TRUE CONFIG_RTNET_NATSEMI_FALSE CONFIG_RTNET_TULIP_TRUE CONFIG_RTNET_TULIP_FALSE CONFIG_RTNET_FCC_ENET_TRUE CONFIG_RTNET_FCC_ENET_FALSE CONFIG_RTNET_SCC_ENET_TRUE CONFIG_RTNET_SCC_ENET_FALSE CONFIG_RTNET_FEC_ENET_TRUE CONFIG_RTNET_FEC_ENET_FALSE CONFIG_RTNET_SMC91111_TRUE CONFIG_RTNET_SMC91111_FALSE CONFIG_RTNET_LOOPBACK_TRUE CONFIG_RTNET_LOOPBACK_FALSE CONFIG_RTNET_RTCFG_TRUE CONFIG_RTNET_RTCFG_FALSE CONFIG_RTNET_RTCAP_TRUE CONFIG_RTNET_RTCAP_FALSE CONFIG_RTNET_PROXY_TRUE CONFIG_RTNET_PROXY_FALSE CONFIG_RTNET_ENCLOSED_RTAI_RTDM_TRUE CONFIG_RTNET_ENCLOSED_RTAI_RTDM_FALSE CONFIG_RTNET_TDMAV1_TRUE CONFIG_RTNET_TDMAV1_FALSE CONFIG_RTNET_NOMAC_TRUE CONFIG_RTNET_NOMAC_FALSE CONFIG_RTNET_RTDM_SELECT_TRUE CONFIG_RTNET_RTDM_SELECT_FALSE CONFIG_RTNET_EXAMPLES_TRUE CONFIG_RTNET_EXAMPLES_FALSE RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LD CONFIG_NCURSES_TRUE CONFIG_NCURSES_FALSE NCURSES_LIBS LIBOBJS CONFIG_FUSION_TRUE CONFIG_FUSION_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE RTNET_TARGET_ARCH CROSS_COMPILE RTNET_MODULE_EXT RTNET_KBUILD_ENV RTNET_KBUILD_CMD RTNET_KBUILD_CLEAN RTNET_MODULE_DIR CONFIG_NEWLXRT_TRUE CONFIG_NEWLXRT_FALSE CONFIG_RTNET_3C59X_TRUE CONFIG_RTNET_3C59X_FALSE CONFIG_RTNET_8139_TRUE CONFIG_RTNET_8139_FALSE CONFIG_RTNET_EEPRO100_TRUE CONFIG_RTNET_EEPRO100_FALSE CONFIG_RTNET_PCNET32_TRUE CONFIG_RTNET_PCNET32_FALSE CONFIG_RTNET_VIA_RHINE_TRUE CONFIG_RTNET_VIA_RHINE_FALSE CONFIG_RTNET_NATSEMI_TRUE CONFIG_RTNET_NATSEMI_FALSE CONFIG_RTNET_TULIP_TRUE CONFIG_RTNET_TULIP_FALSE CONFIG_RTNET_FCC_ENET_TRUE CONFIG_RTNET_FCC_ENET_FALSE CONFIG_RTNET_SCC_ENET_TRUE CONFIG_RTNET_SCC_ENET_FALSE CONFIG_RTNET_FEC_ENET_TRUE CONFIG_RTNET_FEC_ENET_FALSE CONFIG_RTNET_SMC91111_TRUE CONFIG_RTNET_SMC91111_FALSE CONFIG_RTNET_LOOPBACK_TRUE CONFIG_RTNET_LOOPBACK_FALSE CONFIG_RTNET_RTCFG_TRUE CONFIG_RTNET_RTCFG_FALSE CONFIG_RTNET_RTCAP_TRUE CONFIG_RTNET_RTCAP_FALSE CONFIG_RTNET_PROXY_TRUE CONFIG_RTNET_PROXY_FALSE CONFIG_RTNET_ENCLOSED_RTAI_RTDM_TRUE CONFIG_RTNET_ENCLOSED_RTAI_RTDM_FALSE CONFIG_RTNET_TDMAV1_TRUE CONFIG_RTNET_TDMAV1_FALSE CONFIG_RTNET_NOMAC_TRUE CONFIG_RTNET_NOMAC_FALSE CONFIG_RTNET_RTDM_SELECT_TRUE CONFIG_RTNET_RTDM_SELECT_FALSE CONFIG_RTNET_EXAMPLES_TRUE CONFIG_RTNET_EXAMPLES_FALSE RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS RTAI_LIBRARIES LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20766,8 +20766,11 @@ echo $ECHO_N "checking for RTAI version... $ECHO_C" >&6
     3.2*)
 	CONFIG_RTNET_RTAI_VERSION=32
 	;;
-    0.7*-fusion)
+    0.7-fusion | 0.7.1-fusion)
 	CONFIG_RTNET_RTAI_VERSION=fusion-07
+	;;
+    0.7.2-fusion)
+	CONFIG_RTNET_RTAI_VERSION=fusion-072
 	;;
     *)
 	{ { echo "$as_me:$LINENO: error: *** Unsupported RTAI version $CONFIG_RTNET_RTAI_3_VERSION in $RTAI_DIR" >&5
@@ -20833,7 +20836,7 @@ echo "$as_me: error: *** Please enable fifos in RTAI" >&2;}
 
 	    ;;
 
-	fusion-07)	# ---> FUSION <---
+	fusion-07*)	# ---> FUSION <---
 
 	    # check for native RTAI skin, needed by rtnet
 	    echo "$as_me:$LINENO: checking for RTAI native skin" >&5
@@ -20957,12 +20960,31 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 	;;
+    fusion-072)
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_FUSION_072 1
+_ACEOF
+
+	;;
     *)
 	{ { echo "$as_me:$LINENO: error: *** No RTAI found in $with_rtai" >&5
 echo "$as_me: error: *** No RTAI found in $with_rtai" >&2;}
    { (exit 1); exit 1; }; }
 	;;
 esac
+
+
+
+if test "$CONFIG_RTNET_RTAI_VERSION" = fusion-07 || \
+                              test "$CONFIG_RTNET_RTAI_VERSION" = fusion-072; then
+  CONFIG_FUSION_TRUE=
+  CONFIG_FUSION_FALSE='#'
+else
+  CONFIG_FUSION_TRUE='#'
+  CONFIG_FUSION_FALSE=
+fi
+
 
 
 
@@ -21022,9 +21044,10 @@ case "${CONFIG_RTNET_RTAI_VERSION}" in
 	RTAI_USER_CFLAGS="`${RTAI_CONFIG} --lxrt-cflags`"
 	CONFIG_RTNET_RTAI_ARCH="`${RTAI_CONFIG} --arch`"
 	;;
-    fusion-07)
+    fusion-07*)
 	RTAI_USER_CFLAGS="`${RTAI_CONFIG} --fusion-cflags`"
 	CONFIG_RTNET_RTAI_ARCH="`${RTAI_CONFIG} --arch`"
+	RTAI_LIBRARIES="`${RTAI_CONFIG} --library-dir`"
 	;;
     *)
 	{ { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -21044,7 +21067,7 @@ echo "$as_me: error: *** internal error" >&2;}
 	31 | 32)
 	    RTAI_KMOD_CFLAGS="`${RTAI_CONFIG} --lxrt-cflags`"
 	    ;;
-	fusion-07)
+	fusion-07*)
 	    RTAI_KMOD_CFLAGS="`${RTAI_CONFIG} --fusion-cflags`"
 	    ;;
 	*)
@@ -21061,7 +21084,7 @@ else
 	30 | 31 | 32)
 	    RTAI_KMOD_CFLAGS="`${RTAI_CONFIG} --module-cflags`"
 	    ;;
-	fusion-07)
+	fusion-07*)
 	    { { echo "$as_me:$LINENO: error: *** internal error" >&5
 echo "$as_me: error: *** internal error" >&2;}
    { (exit 1); exit 1; }; }
@@ -21293,7 +21316,7 @@ fi
 done
 
             ;;
-	fusion-07)
+	fusion-07*)
 
 
 
@@ -21504,7 +21527,7 @@ fi
 done
 
 	    ;;
-	fusion-07)
+	fusion-07*)
 	    { { echo "$as_me:$LINENO: error: *** internal error" >&5
 echo "$as_me: error: *** internal error" >&2;}
    { (exit 1); exit 1; }; }
@@ -21558,7 +21581,7 @@ case "${CONFIG_RTNET_RTAI_VERSION}" in
 	    *) CONFIG_NEWLXRT=no ;;
 	esac
 	;;
-    fusion-07) CONFIG_NEWLXRT=no
+    fusion-07*) CONFIG_NEWLXRT=no
 	;;
     *)
 	{ { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -22322,6 +22345,7 @@ RTAI_USER_CFLAGS="-D__IN_RTNET__ $RTAI_USER_CFLAGS"
 
 
 
+
 if test x$CONFIG_KBUILD = xy; then
     for DIR in \
 	addons/examples/frag-ip \
@@ -22370,7 +22394,7 @@ fi
 
 
 
-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ac_config_files="$ac_config_files GNUmakefile Documentation/GNUmakefile addons/GNUmakefile addons/examples/GNUmakefile addons/examples/frag-ip/GNUmakefile addons/examples/lxrt/GNUmakefile addons/examples/raw-packets/GNUmakefile addons/examples/round-trip-time/GNUmakefile addons/examples/round-trip-time/client/GNUmakefile addons/examples/round-trip-time/linux-client/GNUmakefile addons/examples/round-trip-time/server/GNUmakefile addons/examples/rtmac/GNUmakefile addons/examples/rtmac/event/GNUmakefile addons/examples/rtmac/event/collector/GNUmakefile addons/examples/rtmac/event/handler/GNUmakefile addons/examples/rtmac/netshm/GNUmakefile addons/examples/rtmac/netshm/kernel-demo/GNUmakefile addons/examples/rtmac/round-trip-time/GNUmakefile addons/examples/rtmac/round-trip-time/client/GNUmakefile addons/examples/rtmac/round-trip-time/multi-client/GNUmakefile addons/examples/rtmac/round-trip-time/parport-client/GNUmakefile addons/examples/rtmac/round-trip-time/server/GNUmakefile addons/examples/select/GNUmakefile addons/rtcap/GNUmakefile addons/rtnetproxy/GNUmakefile drivers/GNUmakefile drivers/8139too/GNUmakefile drivers/eepro100/GNUmakefile drivers/loopback/GNUmakefile drivers/mpc8260_fcc_enet/GNUmakefile drivers/mpc8xx_enet/GNUmakefile drivers/mpc8xx_fec/GNUmakefile drivers/natsemi/GNUmakefile drivers/pcnet32/GNUmakefile drivers/smc91111/GNUmakefile drivers/tulip/GNUmakefile drivers/via-rhine/GNUmakefile drivers/experimental/GNUmakefile drivers/experimental/3c59x/GNUmakefile rtai_rtdm/GNUmakefile stack/GNUmakefile stack/include/GNUmakefile stack/rtcfg/GNUmakefile stack/rtmac/GNUmakefile stack/rtmac/nomac/GNUmakefile stack/rtmac/tdma/GNUmakefile stack/rtmac/tdma-v1/GNUmakefile tools/GNUmakefile tools/rtnet tools/rtnet.conf tools/rtnet-tdma-v1"
+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ac_config_files="$ac_config_files GNUmakefile Documentation/GNUmakefile addons/GNUmakefile addons/examples/GNUmakefile addons/examples/frag-ip/GNUmakefile addons/examples/fusion/GNUmakefile addons/examples/lxrt/GNUmakefile addons/examples/raw-packets/GNUmakefile addons/examples/round-trip-time/GNUmakefile addons/examples/round-trip-time/client/GNUmakefile addons/examples/round-trip-time/linux-client/GNUmakefile addons/examples/round-trip-time/server/GNUmakefile addons/examples/rtmac/GNUmakefile addons/examples/rtmac/event/GNUmakefile addons/examples/rtmac/event/collector/GNUmakefile addons/examples/rtmac/event/handler/GNUmakefile addons/examples/rtmac/netshm/GNUmakefile addons/examples/rtmac/netshm/kernel-demo/GNUmakefile addons/examples/rtmac/round-trip-time/GNUmakefile addons/examples/rtmac/round-trip-time/client/GNUmakefile addons/examples/rtmac/round-trip-time/multi-client/GNUmakefile addons/examples/rtmac/round-trip-time/parport-client/GNUmakefile addons/examples/rtmac/round-trip-time/server/GNUmakefile addons/examples/select/GNUmakefile addons/rtcap/GNUmakefile addons/rtnetproxy/GNUmakefile drivers/GNUmakefile drivers/8139too/GNUmakefile drivers/eepro100/GNUmakefile drivers/loopback/GNUmakefile drivers/mpc8260_fcc_enet/GNUmakefile drivers/mpc8xx_enet/GNUmakefile drivers/mpc8xx_fec/GNUmakefile drivers/natsemi/GNUmakefile drivers/pcnet32/GNUmakefile drivers/smc91111/GNUmakefile drivers/tulip/GNUmakefile drivers/via-rhine/GNUmakefile drivers/experimental/GNUmakefile drivers/experimental/3c59x/GNUmakefile rtai_rtdm/GNUmakefile stack/GNUmakefile stack/include/GNUmakefile stack/rtcfg/GNUmakefile stack/rtmac/GNUmakefile stack/rtmac/nomac/GNUmakefile stack/rtmac/tdma/GNUmakefile stack/rtmac/tdma-v1/GNUmakefile tools/GNUmakefile tools/rtnet tools/rtnet.conf tools/rtnet-tdma-v1"
 
 
 cat >confcache <<\_ACEOF
@@ -22496,6 +22520,13 @@ if test -z "${CONFIG_NCURSES_TRUE}" && test -z "${CONFIG_NCURSES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_NCURSES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_NCURSES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_FUSION_TRUE}" && test -z "${CONFIG_FUSION_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_FUSION\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_FUSION\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23105,6 +23136,7 @@ do
   "addons/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/GNUmakefile" ;;
   "addons/examples/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/examples/GNUmakefile" ;;
   "addons/examples/frag-ip/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/examples/frag-ip/GNUmakefile" ;;
+  "addons/examples/fusion/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/examples/fusion/GNUmakefile" ;;
   "addons/examples/lxrt/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/examples/lxrt/GNUmakefile" ;;
   "addons/examples/raw-packets/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/examples/raw-packets/GNUmakefile" ;;
   "addons/examples/round-trip-time/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES addons/examples/round-trip-time/GNUmakefile" ;;
@@ -23317,6 +23349,8 @@ s,@CONFIG_NCURSES_TRUE@,$CONFIG_NCURSES_TRUE,;t t
 s,@CONFIG_NCURSES_FALSE@,$CONFIG_NCURSES_FALSE,;t t
 s,@NCURSES_LIBS@,$NCURSES_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
+s,@CONFIG_FUSION_TRUE@,$CONFIG_FUSION_TRUE,;t t
+s,@CONFIG_FUSION_FALSE@,$CONFIG_FUSION_FALSE,;t t
 s,@CONFIG_KBUILD_TRUE@,$CONFIG_KBUILD_TRUE,;t t
 s,@CONFIG_KBUILD_FALSE@,$CONFIG_KBUILD_FALSE,;t t
 s,@RTNET_TARGET_ARCH@,$RTNET_TARGET_ARCH,;t t
@@ -23370,6 +23404,7 @@ s,@CONFIG_RTNET_EXAMPLES_TRUE@,$CONFIG_RTNET_EXAMPLES_TRUE,;t t
 s,@CONFIG_RTNET_EXAMPLES_FALSE@,$CONFIG_RTNET_EXAMPLES_FALSE,;t t
 s,@RTAI_KMOD_CFLAGS@,$RTAI_KMOD_CFLAGS,;t t
 s,@RTAI_USER_CFLAGS@,$RTAI_USER_CFLAGS,;t t
+s,@RTAI_LIBRARIES@,$RTAI_LIBRARIES,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
