* added support for new xenomai build system
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@916 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -1098,6 +1098,7 @@ Optional Packages:
   --with-rtext=RT-EXTENSION
                           installation path of RTAI or Xenomai
   --with-rtfw=RTFW        installation path of RT-FireWire
+  --with-linux=LINUX      real-time extended Linux kernel
   --with-module-dir=<module-dir>
                           Installation directory for modules
 
@@ -3787,7 +3788,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3790 "configure"' > conftest.$ac_ext
+  echo '#line 3791 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5366,7 +5367,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5369:" \
+echo "$as_me:5370:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6464,11 +6465,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6467: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6468: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6471: \$? = $ac_status" >&5
+   echo "$as_me:6472: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6726,11 +6727,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6729: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6730: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6733: \$? = $ac_status" >&5
+   echo "$as_me:6734: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6788,11 +6789,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6791: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6795: \$? = $ac_status" >&5
+   echo "$as_me:6796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9028,7 +9029,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9031 "configure"
+#line 9032 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9126,7 +9127,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9129 "configure"
+#line 9130 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11374,11 +11375,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11377: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11378: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11381: \$? = $ac_status" >&5
+   echo "$as_me:11382: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11436,11 +11437,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11439: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11440: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11443: \$? = $ac_status" >&5
+   echo "$as_me:11444: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12805,7 +12806,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12808 "configure"
+#line 12809 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12903,7 +12904,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12906 "configure"
+#line 12907 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13788,11 +13789,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13791: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13795: \$? = $ac_status" >&5
+   echo "$as_me:13796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13850,11 +13851,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13853: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13854: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13857: \$? = $ac_status" >&5
+   echo "$as_me:13858: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15972,11 +15973,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15975: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15976: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15979: \$? = $ac_status" >&5
+   echo "$as_me:15980: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16234,11 +16235,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16237: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16238: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16241: \$? = $ac_status" >&5
+   echo "$as_me:16242: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16296,11 +16297,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16299: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16300: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16303: \$? = $ac_status" >&5
+   echo "$as_me:16304: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18536,7 +18537,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18539 "configure"
+#line 18540 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18634,7 +18635,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18637 "configure"
+#line 18638 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19878,7 +19879,7 @@ if test "${with_rtfw+set}" = set; then
 echo "$as_me: error: You must supply an argument to --with-rtfw." >&2;}
    { (exit 1); exit 1; }; } ;;
         *)
-            CONFIG_RTFIREWIRE_DIR=${withval} ;;
+            CONFIG_RTNET_RTFIREWIRE_DIR=${withval} ;;
     esac
 fi;
 
@@ -19976,6 +19977,12 @@ echo "${ECHO_T}${RTAI_CONFIG_FILE}" >&6
     # source (load) the rtai configuration
     . ${RTAI_CONFIG_FILE}
 
+    # get linux kernel tree and version
+    echo "$as_me:$LINENO: checking for Linux source tree" >&5
+echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
+    RTEXT_LINUX_DIR="`${RTAI_CONFIG} --linux-dir`"
+    RTEXT_LINUX_VERSION="`${RTAI_CONFIG} --linux-version`"
+
 elif test "$XENO_DIR" \!= ""; then
     #
     # check if Xenomai is installed with DESTDIR
@@ -20007,12 +20014,70 @@ echo $ECHO_N "checking for Xenomai version... $ECHO_C" >&6
     XENO_VERSION="`${XENO_CONFIG} --version`"
 
     case "$XENO_VERSION" in
-        1.9.9 | 2.*)
-            CONFIG_RTNET_RTEXT_VERSION=xeno-2x
+        1.9.9 | 2.0*)
+            CONFIG_RTNET_RTEXT_VERSION=xeno-20x
 
 cat >>confdefs.h <<\_ACEOF
 #define CONFIG_XENO_2x 1
 _ACEOF
+
+            echo "$as_me:$LINENO: result: ${XENO_VERSION}" >&5
+echo "${ECHO_T}${XENO_VERSION}" >&6
+
+            echo "$as_me:$LINENO: checking for Xenomai config file" >&5
+echo $ECHO_N "checking for Xenomai config file... $ECHO_C" >&6
+            XENO_CONFIG_FILE="`${XENO_CONFIG} --config`"
+            if test \! -f $XENO_CONFIG_FILE; then
+                { { echo "$as_me:$LINENO: error: *** Xenomai configuration file not found" >&5
+echo "$as_me: error: *** Xenomai configuration file not found" >&2;}
+   { (exit 1); exit 1; }; }
+            fi
+            echo "$as_me:$LINENO: result: ${XENO_CONFIG_FILE}" >&5
+echo "${ECHO_T}${XENO_CONFIG_FILE}" >&6
+
+            # source (load) the Xenomai configuration
+            . ${XENO_CONFIG_FILE}
+
+            # get linux kernel tree and version
+            echo "$as_me:$LINENO: checking for Linux source tree" >&5
+echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
+            RTEXT_LINUX_DIR="`${XENO_CONFIG} --linux-dir`"
+            RTEXT_LINUX_VERSION="`${XENO_CONFIG} --linux-version`"
+
+            ;;
+        2.1*)
+            CONFIG_RTNET_RTEXT_VERSION=xeno-21x
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_XENO_2x 1
+_ACEOF
+
+            echo "$as_me:$LINENO: result: ${XENO_VERSION}" >&5
+echo "${ECHO_T}${XENO_VERSION}" >&6
+
+
+# Check whether --with-linux or --without-linux was given.
+if test "${with_linux+set}" = set; then
+  withval="$with_linux"
+  case "${withval}" in
+                    "" | y | ye | yes | n | no)
+                        { { echo "$as_me:$LINENO: error: You must supply an argument to --with-linux." >&5
+echo "$as_me: error: You must supply an argument to --with-linux." >&2;}
+   { (exit 1); exit 1; }; } ;;
+                    *)
+                        CONFIG_RTNET_LINUX_DIR=${withval} ;;
+                esac
+fi;
+
+            # get linux kernel tree and version
+            echo "$as_me:$LINENO: checking for Linux source tree" >&5
+echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
+            RTEXT_LINUX_DIR="${CONFIG_RTNET_LINUX_DIR}"
+            eval linux_`grep '^EXTRAVERSION =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
+            eval linux_`grep '^PATCHLEVEL =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
+            eval linux_`grep '^SUBLEVEL =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
+            eval linux_`grep '^VERSION =' $RTEXT_LINUX_DIR/Makefile | sed -e 's, ,,g'`
+            RTEXT_LINUX_VERSION="$linux_VERSION.$linux_PATCHLEVEL.$linux_SUBLEVEL$linux_EXTRAVERSION"
 
             ;;
         *)
@@ -20021,28 +20086,18 @@ echo "$as_me: error: *** Unsupported Xenomai version $XENO_VERSION in $XENO_DIR"
    { (exit 1); exit 1; }; }
             ;;
     esac
-    echo "$as_me:$LINENO: result: ${XENO_VERSION}" >&5
-echo "${ECHO_T}${XENO_VERSION}" >&6
-
-    echo "$as_me:$LINENO: checking for Xenomai config file" >&5
-echo $ECHO_N "checking for Xenomai config file... $ECHO_C" >&6
-    XENO_CONFIG_FILE="`${XENO_CONFIG} --config`"
-    if test \! -f $XENO_CONFIG_FILE; then
-        { { echo "$as_me:$LINENO: error: *** Xenomai configuration file not found" >&5
-echo "$as_me: error: *** Xenomai configuration file not found" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    echo "$as_me:$LINENO: result: ${XENO_CONFIG_FILE}" >&5
-echo "${ECHO_T}${XENO_CONFIG_FILE}" >&6
-
-    # source (load) the Xenomai configuration
-    . ${XENO_CONFIG_FILE}
 
 else
     { { echo "$as_me:$LINENO: error: *** internal error" >&5
 echo "$as_me: error: *** internal error" >&2;}
    { (exit 1); exit 1; }; }
 fi
+
+#source (load) the kernel configuration
+. ${RTEXT_LINUX_DIR}/.config
+
+echo "$as_me:$LINENO: result: $RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&5
+echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&6
 
 
 
@@ -20101,15 +20156,9 @@ echo "$as_me: error: *** Please enable fifos in RTAI" >&2;}
    { (exit 1); exit 1; }; } ;;
         esac
 
-        # get linux kernel tree and version
-        echo "$as_me:$LINENO: checking for Linux source tree" >&5
-echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
-        RTEXT_LINUX_DIR="`${RTAI_CONFIG} --linux-dir`"
-        RTEXT_LINUX_VERSION="`${RTAI_CONFIG} --linux-version`"
-
         ;;
 
-    xeno-2x) # ---> Xenomai 2.x <---
+    xeno-20x | xeno-21x) # ---> Xenomai 2.x <---
 
         # check for RTDM skin, needed by RTnet
         echo "$as_me:$LINENO: checking for RTDM skin" >&5
@@ -20129,12 +20178,6 @@ echo "$as_me: error: *** Please enable RTDM skin" >&2;}
 #            *) AC_MSG_ERROR([*** Please enable pipes in RTAI]) ;;
 #        esac
 
-        # get linux kernel tree and version
-        echo "$as_me:$LINENO: checking for Linux source tree" >&5
-echo $ECHO_N "checking for Linux source tree... $ECHO_C" >&6
-        RTEXT_LINUX_DIR="`${XENO_CONFIG} --linux-dir`"
-        RTEXT_LINUX_VERSION="`${XENO_CONFIG} --linux-version`"
-
         ;;
 
     *)              # ---> oops <----
@@ -20144,12 +20187,6 @@ echo "$as_me: error: *** internal error" >&2;}
         ;;
 esac
 
-#source (load) the kernel configuration
-. ${RTEXT_LINUX_DIR}/.config
-
-echo "$as_me:$LINENO: result: $RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&5
-echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP})" >&6
-
 
 
 #
@@ -20157,9 +20194,9 @@ echo "${ECHO_T}$RTEXT_LINUX_DIR (kernel ${RTEXT_LINUX_VERSION}${CONFIG_SMP:+-SMP
 #
 echo "$as_me:$LINENO: checking for RT-FireWire installation" >&5
 echo $ECHO_N "checking for RT-FireWire installation... $ECHO_C" >&6
-RTFW_SYMBOLS="${CONFIG_RTFIREWIRE_DIR}/symbols"
+RTFW_SYMBOLS="${CONFIG_RTNET_RTFIREWIRE_DIR}/symbols"
 if test -d ${RTFW_SYMBOLS}; then
-    RTNET_RTFW_PREFIX="`echo ${CONFIG_RTFIREWIRE_DIR} | sed -e s,/*$,,`"  # strip trailing slashes
+    RTNET_RTFW_PREFIX="`echo ${CONFIG_RTNET_RTFIREWIRE_DIR} | sed -e s,/*$,,`"  # strip trailing slashes
     echo "$as_me:$LINENO: result: ${RTNET_RTFW_PREFIX}" >&5
 echo "${ECHO_T}${RTNET_RTFW_PREFIX}" >&6
 else
@@ -20222,11 +20259,16 @@ case "${CONFIG_RTNET_RTEXT_VERSION}" in
         CONFIG_RTNET_RTEXT_ARCH="`${RTAI_CONFIG} --arch`"
         RTEXT_LIBRARIES="`${RTAI_CONFIG} --library-dir`"
         ;;
-    xeno-2x)
+    xeno-20x)
         RTEXT_USER_CFLAGS="`${XENO_CONFIG} --xeno-cflags`"
         CONFIG_RTNET_RTEXT_ARCH="`${XENO_CONFIG} --arch`"
         RTEXT_LIBRARIES="`${XENO_CONFIG} --library-dir`"
         RTEXT_SYMBOLS="`${XENO_CONFIG} --symbol-dir`"
+        ;;
+    xeno-21x)
+        RTEXT_USER_CFLAGS="`${XENO_CONFIG} --xeno-cflags`"
+        CONFIG_RTNET_RTEXT_ARCH="`${XENO_CONFIG} --arch`"
+        RTEXT_LIBRARIES="`${XENO_CONFIG} --library-dir`"
         ;;
     *)
         { { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -20241,8 +20283,11 @@ if test "$CONFIG_KBUILD" = "y"; then
         rtai-3x)
             RTEXT_KMOD_CFLAGS="`${RTAI_CONFIG} --module-cflags`"
             ;;
-        xeno-2x)
+        xeno-20x)
             RTEXT_KMOD_CFLAGS="`${XENO_CONFIG} --module-cflags`"
+            ;;
+        xeno-21x)
+            RTEXT_KMOD_CFLAGS="-I ${RTEXT_LINUX_DIR}/include/xenomai"
             ;;
         *)
             { { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -20255,7 +20300,7 @@ else
         rtai-3x)
             RTEXT_KMOD_CFLAGS="`${RTAI_CONFIG} --module-cflags`"
             ;;
-        xeno-2x)
+        xeno-20x | xeno-21x)
             { { echo "$as_me:$LINENO: error: *** internal error" >&5
 echo "$as_me: error: *** internal error" >&2;}
    { (exit 1); exit 1; }; }
@@ -20563,7 +20608,7 @@ fi
 done
 
             ;;
-        xeno-2x)
+        xeno-20x | xeno-21x)
             # nothing further to do
             ;;
         *)
@@ -20713,7 +20758,7 @@ fi
 done
 
             ;;
-        xeno-2x)
+        xeno-20x | xeno-21x)
             { { echo "$as_me:$LINENO: error: *** internal error" >&5
 echo "$as_me: error: *** internal error" >&2;}
    { (exit 1); exit 1; }; }
@@ -20788,7 +20833,7 @@ echo "$as_me: WARNING:
 echo "${ECHO_T}${CONFIG_REGPARM:-n}" >&6
         fi
         ;;
-    xeno-2x) CONFIG_RTNET_LXRT=n
+    xeno-20x | xeno-21x) CONFIG_RTNET_LXRT=n
         ;;
     *)
         { { echo "$as_me:$LINENO: error: *** internal error" >&5
@@ -21661,12 +21706,23 @@ fi
 
 if test x$CONFIG_KBUILD = xy; then
     case "${CONFIG_RTNET_RTEXT_VERSION}" in
-        xeno-2x)
+        xeno-20x)
             mkdir -p symbols
             rm -rf symbols/*
             for FILE in `ls ${RTEXT_SYMBOLS}/*`; do
                 ${LN_S} ${FILE} symbols/$(basename ${FILE})
             done
+            if test -d ${RTFW_SYMBOLS}; then
+                for FILE in `ls ${RTFW_SYMBOLS}/*`; do
+                    if test \! -e symbols/$(basename ${FILE}); then
+                        ${LN_S} ${FILE} symbols/$(basename ${FILE})
+                    fi
+                done
+            fi
+            ;;
+        xeno-21x)
+            mkdir -p symbols
+            rm -rf symbols/*
             if test -d ${RTFW_SYMBOLS}; then
                 for FILE in `ls ${RTFW_SYMBOLS}/*`; do
                     if test \! -e symbols/$(basename ${FILE}); then
