added experimental e1000 driver by Mathias
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@1038 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT RTNET_HOST_STRING CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LD CONFIG_NCURSES_TRUE CONFIG_NCURSES_FALSE NCURSES_LIBS CONFIG_RTAI_TRUE CONFIG_RTAI_FALSE CONFIG_XENO_TRUE CONFIG_XENO_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE RTNET_TARGET_ARCH CROSS_COMPILE RTNET_MODULE_EXT RTNET_KBUILD_ENV RTNET_KBUILD_CMD RTNET_KBUILD_CLEAN RTNET_KBUILD_DISTCLEAN RTNET_MODULE_DIR CONFIG_RTNET_LXRT_TRUE CONFIG_RTNET_LXRT_FALSE CONFIG_RTNET_DRV_8139_TRUE CONFIG_RTNET_DRV_8139_FALSE CONFIG_RTNET_DRV_EEPRO100_TRUE CONFIG_RTNET_DRV_EEPRO100_FALSE CONFIG_RTNET_DRV_PCNET32_TRUE CONFIG_RTNET_DRV_PCNET32_FALSE CONFIG_RTNET_DRV_VIA_RHINE_TRUE CONFIG_RTNET_DRV_VIA_RHINE_FALSE CONFIG_RTNET_DRV_NATSEMI_TRUE CONFIG_RTNET_DRV_NATSEMI_FALSE CONFIG_RTNET_DRV_TULIP_TRUE CONFIG_RTNET_DRV_TULIP_FALSE CONFIG_RTNET_DRV_FCC_ENET_TRUE CONFIG_RTNET_DRV_FCC_ENET_FALSE CONFIG_RTNET_DRV_SCC_ENET_TRUE CONFIG_RTNET_DRV_SCC_ENET_FALSE CONFIG_RTNET_DRV_FEC_ENET_TRUE CONFIG_RTNET_DRV_FEC_ENET_FALSE CONFIG_RTNET_DRV_MPC52XX_FEC_TRUE CONFIG_RTNET_DRV_MPC52XX_FEC_FALSE CONFIG_RTNET_DRV_SMC91111_TRUE CONFIG_RTNET_DRV_SMC91111_FALSE CONFIG_RTNET_DRV_ETH1394_TRUE CONFIG_RTNET_DRV_ETH1394_FALSE CONFIG_RTNET_DRV_LOOPBACK_TRUE CONFIG_RTNET_DRV_LOOPBACK_FALSE CONFIG_RTNET_DRV_3C59X_TRUE CONFIG_RTNET_DRV_3C59X_FALSE CONFIG_RTNET_DRV_R8169_TRUE CONFIG_RTNET_DRV_R8169_FALSE CONFIG_RTNET_DRV_RT2500_TRUE CONFIG_RTNET_DRV_RT2500_FALSE CONFIG_RTNET_RTWLAN_TRUE CONFIG_RTNET_RTWLAN_FALSE CONFIG_RTNET_RTIPV4_TRUE CONFIG_RTNET_RTIPV4_FALSE CONFIG_RTNET_RTPACKET_TRUE CONFIG_RTNET_RTPACKET_FALSE CONFIG_RTNET_RTCFG_TRUE CONFIG_RTNET_RTCFG_FALSE CONFIG_RTNET_RTMAC_TRUE CONFIG_RTNET_RTMAC_FALSE CONFIG_RTNET_TDMA_TRUE CONFIG_RTNET_TDMA_FALSE CONFIG_RTNET_NOMAC_TRUE CONFIG_RTNET_NOMAC_FALSE CONFIG_RTNET_ADDON_RTCAP_TRUE CONFIG_RTNET_ADDON_RTCAP_FALSE CONFIG_RTNET_ADDON_PROXY_TRUE CONFIG_RTNET_ADDON_PROXY_FALSE CONFIG_RTNET_EXAMPLES_TRUE CONFIG_RTNET_EXAMPLES_FALSE RTEXT_KMOD_CFLAGS RTEXT_USER_CFLAGS XNPOSIX_USER_CFLAGS XNPOSIX_USER_LDFLAGS RTEXT_LIBRARIES RTFW_KMOD_CFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT RTNET_HOST_STRING CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LD CONFIG_NCURSES_TRUE CONFIG_NCURSES_FALSE NCURSES_LIBS CONFIG_RTAI_TRUE CONFIG_RTAI_FALSE CONFIG_XENO_TRUE CONFIG_XENO_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE RTNET_TARGET_ARCH CROSS_COMPILE RTNET_MODULE_EXT RTNET_KBUILD_ENV RTNET_KBUILD_CMD RTNET_KBUILD_CLEAN RTNET_KBUILD_DISTCLEAN RTNET_MODULE_DIR CONFIG_RTNET_LXRT_TRUE CONFIG_RTNET_LXRT_FALSE CONFIG_RTNET_DRV_8139_TRUE CONFIG_RTNET_DRV_8139_FALSE CONFIG_RTNET_DRV_EEPRO100_TRUE CONFIG_RTNET_DRV_EEPRO100_FALSE CONFIG_RTNET_DRV_PCNET32_TRUE CONFIG_RTNET_DRV_PCNET32_FALSE CONFIG_RTNET_DRV_VIA_RHINE_TRUE CONFIG_RTNET_DRV_VIA_RHINE_FALSE CONFIG_RTNET_DRV_NATSEMI_TRUE CONFIG_RTNET_DRV_NATSEMI_FALSE CONFIG_RTNET_DRV_TULIP_TRUE CONFIG_RTNET_DRV_TULIP_FALSE CONFIG_RTNET_DRV_FCC_ENET_TRUE CONFIG_RTNET_DRV_FCC_ENET_FALSE CONFIG_RTNET_DRV_SCC_ENET_TRUE CONFIG_RTNET_DRV_SCC_ENET_FALSE CONFIG_RTNET_DRV_FEC_ENET_TRUE CONFIG_RTNET_DRV_FEC_ENET_FALSE CONFIG_RTNET_DRV_MPC52XX_FEC_TRUE CONFIG_RTNET_DRV_MPC52XX_FEC_FALSE CONFIG_RTNET_DRV_SMC91111_TRUE CONFIG_RTNET_DRV_SMC91111_FALSE CONFIG_RTNET_DRV_ETH1394_TRUE CONFIG_RTNET_DRV_ETH1394_FALSE CONFIG_RTNET_DRV_LOOPBACK_TRUE CONFIG_RTNET_DRV_LOOPBACK_FALSE CONFIG_RTNET_DRV_3C59X_TRUE CONFIG_RTNET_DRV_3C59X_FALSE CONFIG_RTNET_DRV_R8169_TRUE CONFIG_RTNET_DRV_R8169_FALSE CONFIG_RTNET_DRV_RT2500_TRUE CONFIG_RTNET_DRV_RT2500_FALSE CONFIG_RTNET_DRV_E1000_TRUE CONFIG_RTNET_DRV_E1000_FALSE CONFIG_RTNET_RTWLAN_TRUE CONFIG_RTNET_RTWLAN_FALSE CONFIG_RTNET_RTIPV4_TRUE CONFIG_RTNET_RTIPV4_FALSE CONFIG_RTNET_RTPACKET_TRUE CONFIG_RTNET_RTPACKET_FALSE CONFIG_RTNET_RTCFG_TRUE CONFIG_RTNET_RTCFG_FALSE CONFIG_RTNET_RTMAC_TRUE CONFIG_RTNET_RTMAC_FALSE CONFIG_RTNET_TDMA_TRUE CONFIG_RTNET_TDMA_FALSE CONFIG_RTNET_NOMAC_TRUE CONFIG_RTNET_NOMAC_FALSE CONFIG_RTNET_ADDON_RTCAP_TRUE CONFIG_RTNET_ADDON_RTCAP_FALSE CONFIG_RTNET_ADDON_PROXY_TRUE CONFIG_RTNET_ADDON_PROXY_FALSE CONFIG_RTNET_EXAMPLES_TRUE CONFIG_RTNET_EXAMPLES_FALSE RTEXT_KMOD_CFLAGS RTEXT_USER_CFLAGS XNPOSIX_USER_CFLAGS XNPOSIX_USER_LDFLAGS RTEXT_LIBRARIES RTFW_KMOD_CFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1066,6 +1066,7 @@ Optional Features:
   --enable-3c59x          build 3Com 59x driver
   --enable-r8169          build Realtek 8169 (Gigabit) driver
   --enable-rt2500         build Ralink 2500 WLAN driver
+  --enable-e1000          build Intel PRO/1000 driver
   --with-rxfifosize       Set RX-FIFO size
   --enable-rtwlan         enable real-time WLAN support [default=no]
   --enable-rtipv4         enable real-time IPv4 support [default=yes]
@@ -3809,7 +3810,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3812 "configure"' > conftest.$ac_ext
+  echo '#line 3813 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5408,7 +5409,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5411:" \
+echo "$as_me:5412:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6471,11 +6472,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6474: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6475: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6478: \$? = $ac_status" >&5
+   echo "$as_me:6479: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6739,11 +6740,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6742: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6743: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6746: \$? = $ac_status" >&5
+   echo "$as_me:6747: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6843,11 +6844,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6846: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6847: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6850: \$? = $ac_status" >&5
+   echo "$as_me:6851: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9188,7 +9189,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9191 "configure"
+#line 9192 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9288,7 +9289,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9291 "configure"
+#line 9292 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11628,11 +11629,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11631: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11632: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11635: \$? = $ac_status" >&5
+   echo "$as_me:11636: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11732,11 +11733,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11735: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11736: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11739: \$? = $ac_status" >&5
+   echo "$as_me:11740: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13302,11 +13303,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13305: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13306: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13309: \$? = $ac_status" >&5
+   echo "$as_me:13310: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13406,11 +13407,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13409: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13410: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13413: \$? = $ac_status" >&5
+   echo "$as_me:13414: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15609,11 +15610,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15612: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15613: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15616: \$? = $ac_status" >&5
+   echo "$as_me:15617: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15877,11 +15878,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15880: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15881: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15884: \$? = $ac_status" >&5
+   echo "$as_me:15885: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15981,11 +15982,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15984: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15985: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15988: \$? = $ac_status" >&5
+   echo "$as_me:15989: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20269,6 +20270,29 @@ else
 fi
 
 
+echo "$as_me:$LINENO: checking whether to build Intel PRO/1000 (Gigabit) driver" >&5
+echo $ECHO_N "checking whether to build Intel PRO/1000 (Gigabit) driver... $ECHO_C" >&6
+# Check whether --enable-e1000 or --disable-e1000 was given.
+if test "${enable_e1000+set}" = set; then
+  enableval="$enable_e1000"
+  case "$enableval" in
+        y | yes) CONFIG_RTNET_DRV_E1000=y ;;
+        *) CONFIG_RTNET_DRV_E1000=n ;;
+    esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTNET_DRV_E1000:-n}" >&5
+echo "${ECHO_T}${CONFIG_RTNET_DRV_E1000:-n}" >&6
+
+
+if test "$CONFIG_RTNET_DRV_E1000" = "y"; then
+  CONFIG_RTNET_DRV_E1000_TRUE=
+  CONFIG_RTNET_DRV_E1000_FALSE='#'
+else
+  CONFIG_RTNET_DRV_E1000_TRUE='#'
+  CONFIG_RTNET_DRV_E1000_FALSE=
+fi
+
+
 
 
 echo "$as_me:$LINENO: checking for RX-FIFO size" >&5
@@ -20753,6 +20777,7 @@ if test x$CONFIG_KBUILD = xy; then
         drivers/tulip \
         drivers/experimental \
         drivers/experimental/rt2500 \
+        drivers/experimental/e1000 \
         \
         stack \
         stack/packet \
@@ -20806,7 +20831,7 @@ fi
 
 
 
-                                                                                                                                                                                                                                                                                                  ac_config_files="$ac_config_files GNUmakefile Documentation/GNUmakefile drivers/GNUmakefile drivers/mpc52xx_fec/GNUmakefile drivers/tulip/GNUmakefile drivers/experimental/GNUmakefile drivers/experimental/rt2500/GNUmakefile stack/GNUmakefile stack/include/GNUmakefile stack/packet/GNUmakefile stack/ipv4/GNUmakefile stack/rtcfg/GNUmakefile stack/rtmac/GNUmakefile stack/rtmac/nomac/GNUmakefile stack/rtmac/tdma/GNUmakefile tools/GNUmakefile tools/rtnet tools/rtnet.conf addons/GNUmakefile examples/GNUmakefile examples/generic/GNUmakefile examples/rtai/GNUmakefile examples/xenomai/GNUmakefile examples/xenomai/native/GNUmakefile examples/xenomai/native/kernel/GNUmakefile examples/xenomai/posix/GNUmakefile scripts/GNUmakefile scripts/kconfig/GNUmakefile scripts/kconfig/lxdialog/GNUmakefile"
+                                                                                                                                                                                                                                                                                                            ac_config_files="$ac_config_files GNUmakefile Documentation/GNUmakefile drivers/GNUmakefile drivers/mpc52xx_fec/GNUmakefile drivers/tulip/GNUmakefile drivers/experimental/GNUmakefile drivers/experimental/rt2500/GNUmakefile drivers/experimental/e1000/GNUmakefile stack/GNUmakefile stack/include/GNUmakefile stack/packet/GNUmakefile stack/ipv4/GNUmakefile stack/rtcfg/GNUmakefile stack/rtmac/GNUmakefile stack/rtmac/nomac/GNUmakefile stack/rtmac/tdma/GNUmakefile tools/GNUmakefile tools/rtnet tools/rtnet.conf addons/GNUmakefile examples/GNUmakefile examples/generic/GNUmakefile examples/rtai/GNUmakefile examples/xenomai/GNUmakefile examples/xenomai/native/GNUmakefile examples/xenomai/native/kernel/GNUmakefile examples/xenomai/posix/GNUmakefile scripts/GNUmakefile scripts/kconfig/GNUmakefile scripts/kconfig/lxdialog/GNUmakefile"
 
 
 
@@ -21073,6 +21098,13 @@ if test -z "${CONFIG_RTNET_DRV_RT2500_TRUE}" && test -z "${CONFIG_RTNET_DRV_RT25
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_DRV_RT2500\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTNET_DRV_RT2500\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTNET_DRV_E1000_TRUE}" && test -z "${CONFIG_RTNET_DRV_E1000_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_DRV_E1000\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTNET_DRV_E1000\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -21600,6 +21632,7 @@ do
   "drivers/tulip/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES drivers/tulip/GNUmakefile" ;;
   "drivers/experimental/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES drivers/experimental/GNUmakefile" ;;
   "drivers/experimental/rt2500/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES drivers/experimental/rt2500/GNUmakefile" ;;
+  "drivers/experimental/e1000/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES drivers/experimental/e1000/GNUmakefile" ;;
   "stack/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES stack/GNUmakefile" ;;
   "stack/include/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES stack/include/GNUmakefile" ;;
   "stack/packet/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES stack/packet/GNUmakefile" ;;
@@ -21834,6 +21867,8 @@ s,@CONFIG_RTNET_DRV_R8169_TRUE@,$CONFIG_RTNET_DRV_R8169_TRUE,;t t
 s,@CONFIG_RTNET_DRV_R8169_FALSE@,$CONFIG_RTNET_DRV_R8169_FALSE,;t t
 s,@CONFIG_RTNET_DRV_RT2500_TRUE@,$CONFIG_RTNET_DRV_RT2500_TRUE,;t t
 s,@CONFIG_RTNET_DRV_RT2500_FALSE@,$CONFIG_RTNET_DRV_RT2500_FALSE,;t t
+s,@CONFIG_RTNET_DRV_E1000_TRUE@,$CONFIG_RTNET_DRV_E1000_TRUE,;t t
+s,@CONFIG_RTNET_DRV_E1000_FALSE@,$CONFIG_RTNET_DRV_E1000_FALSE,;t t
 s,@CONFIG_RTNET_RTWLAN_TRUE@,$CONFIG_RTNET_RTWLAN_TRUE,;t t
 s,@CONFIG_RTNET_RTWLAN_FALSE@,$CONFIG_RTNET_RTWLAN_FALSE,;t t
 s,@CONFIG_RTNET_RTIPV4_TRUE@,$CONFIG_RTNET_RTIPV4_TRUE,;t t
