* added rtskb-kmalloc switch with check against CONFIG_RTAI_MM_VMALLOC * added pcnet32-rt
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@205 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LN_S RANLIB ac_ct_RANLIB LXRT_LIBS NCURSES_LIBS EGREP LIBOBJS RTAI_DIR RTAI_KMOD_CFLAGS RTAI_CFLAGS KERNEL_CFLAGS CROSS_COMPILE CONFIG_RTNET_3C59X_TRUE CONFIG_RTNET_3C59X_FALSE CONFIG_RTNET_8139_TRUE CONFIG_RTNET_8139_FALSE CONFIG_RTNET_EEPRO100_TRUE CONFIG_RTNET_EEPRO100_FALSE CONFIG_RTNET_LOOPBACK_TRUE CONFIG_RTNET_LOOPBACK_FALSE CONFIG_RTNET_TULIP_TRUE CONFIG_RTNET_TULIP_FALSE CONFIG_RTNET_FCC_ENET_TRUE CONFIG_RTNET_FCC_ENET_FALSE CONFIG_RTNET_SCC_ENET_TRUE CONFIG_RTNET_SCC_ENET_FALSE CONFIG_RTNET_FEC_ENET_TRUE CONFIG_RTNET_FEC_ENET_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LN_S RANLIB ac_ct_RANLIB LXRT_LIBS NCURSES_LIBS EGREP LIBOBJS RTAI_DIR RTAI_KMOD_CFLAGS RTAI_CFLAGS KERNEL_CFLAGS CROSS_COMPILE CONFIG_RTNET_RTSKB_USE_KMALLOC_TRUE CONFIG_RTNET_RTSKB_USE_KMALLOC_FALSE CONFIG_RTNET_3C59X_TRUE CONFIG_RTNET_3C59X_FALSE CONFIG_RTNET_8139_TRUE CONFIG_RTNET_8139_FALSE CONFIG_RTNET_EEPRO100_TRUE CONFIG_RTNET_EEPRO100_FALSE CONFIG_RTNET_PCNET32_TRUE CONFIG_RTNET_PCNET32_FALSE CONFIG_RTNET_LOOPBACK_TRUE CONFIG_RTNET_LOOPBACK_FALSE CONFIG_RTNET_TULIP_TRUE CONFIG_RTNET_TULIP_FALSE CONFIG_RTNET_FCC_ENET_TRUE CONFIG_RTNET_FCC_ENET_FALSE CONFIG_RTNET_SCC_ENET_TRUE CONFIG_RTNET_SCC_ENET_FALSE CONFIG_RTNET_FEC_ENET_TRUE CONFIG_RTNET_FEC_ENET_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -854,9 +854,11 @@ Optional Features:
                           (and sometimes confusing) to the casual installer
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
+  --enable-rtskb-kmalloc use kmalloc instead of rt_malloc for creating/extending rtskb pools
   --enable-3c59x         build 3Com 59x driver
   --enable-8139          build Realtek 8139 driver
   --enable-eepro100      build Intel EtherExpressPro/100 driver
+  --enable-pcnet32       build AMD PCnet32 driver
   --enable-loopback      build loopback driver
   --enable-tulip         build tulip driver
   --enable-fcc-enet      build fcc enet driver
@@ -4770,6 +4772,52 @@ KERNEL_CFLAGS=-I$RTAI_LINUX_DIR/include
 
 
 
+if test \! -r ${RTAI_DIR}/.config; then
+	{ { echo "$as_me:$LINENO: error: *** $RTAI_DIR is not configured" >&5
+echo "$as_me: error: *** $RTAI_DIR is not configured" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+echo "$as_me:$LINENO: checking $RTAI_DIR/.config" >&5
+echo $ECHO_N "checking $RTAI_DIR/.config... $ECHO_C" >&6
+. $RTAI_DIR/.config
+echo "$as_me:$LINENO: result: done" >&5
+echo "${ECHO_T}done" >&6
+
+echo "$as_me:$LINENO: checking whether to use kmalloc for rtskb pools" >&5
+echo $ECHO_N "checking whether to use kmalloc for rtskb pools... $ECHO_C" >&6
+# Check whether --enable-rtskb-kmalloc or --disable-rtskb-kmalloc was given.
+if test "${enable_rtskb_kmalloc+set}" = set; then
+  enableval="$enable_rtskb_kmalloc"
+  case "$enableval" in
+	y | yes ) CONFIG_RTNET_RTSKB_USE_KMALLOC=yes;;
+	*) unset CONFIG_RTNET_RTSKB_USE_KMALLOC ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTNET_RTSKB_USE_KMALLOC:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTNET_RTSKB_USE_KMALLOC:-no}" >&6
+
+
+if test "$CONFIG_RTNET_RTSKB_USE_KMALLOC" = "yes"; then
+  CONFIG_RTNET_RTSKB_USE_KMALLOC_TRUE=
+  CONFIG_RTNET_RTSKB_USE_KMALLOC_FALSE='#'
+else
+  CONFIG_RTNET_RTSKB_USE_KMALLOC_TRUE='#'
+  CONFIG_RTNET_RTSKB_USE_KMALLOC_FALSE=
+fi
+
+
+if test "$CONFIG_RTNET_RTSKB_USE_KMALLOC" = "yes"; then
+	CFLAGS="${CFLAGS} -DCONFIG_RTNET_RTSKB_USE_KMALLOC"
+elif test \! "$CONFIG_RTAI_MM_VMALLOC" = "" ; then
+	{ { echo "$as_me:$LINENO: error: *** RTAI memory manager uses vmalloc. Disable this feature or configure RTnet with --enable-rtskb-kmalloc" >&5
+echo "$as_me: error: *** RTAI memory manager uses vmalloc. Disable this feature or configure RTnet with --enable-rtskb-kmalloc" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+
 echo "$as_me:$LINENO: checking whether to build 3Com 59x driver" >&5
 echo $ECHO_N "checking whether to build 3Com 59x driver... $ECHO_C" >&6
 # Check whether --enable-3c59x or --disable-3c59x was given.
@@ -4838,6 +4886,30 @@ if test "$CONFIG_RTNET_EEPRO100" = "yes"; then
 else
   CONFIG_RTNET_EEPRO100_TRUE='#'
   CONFIG_RTNET_EEPRO100_FALSE=
+fi
+
+
+
+echo "$as_me:$LINENO: checking whether to build AMD PCnet32 driver" >&5
+echo $ECHO_N "checking whether to build AMD PCnet32 driver... $ECHO_C" >&6
+# Check whether --enable-pcnet32 or --disable-pcnet32 was given.
+if test "${enable_pcnet32+set}" = set; then
+  enableval="$enable_pcnet32"
+  case "$enableval" in
+	y | yes ) CONFIG_RTNET_PCNET32=yes;;
+	*) unset CONFIG_RTNET_PCNET32 ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTNET_PCNET32:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTNET_PCNET32:-no}" >&6
+
+
+if test "$CONFIG_RTNET_PCNET32" = "yes"; then
+  CONFIG_RTNET_PCNET32_TRUE=
+  CONFIG_RTNET_PCNET32_FALSE='#'
+else
+  CONFIG_RTNET_PCNET32_TRUE='#'
+  CONFIG_RTNET_PCNET32_FALSE=
 fi
 
 
@@ -5076,6 +5148,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RTNET_RTSKB_USE_KMALLOC_TRUE}" && test -z "${CONFIG_RTNET_RTSKB_USE_KMALLOC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_RTSKB_USE_KMALLOC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTNET_RTSKB_USE_KMALLOC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RTNET_3C59X_TRUE}" && test -z "${CONFIG_RTNET_3C59X_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_3C59X\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -5094,6 +5173,13 @@ if test -z "${CONFIG_RTNET_EEPRO100_TRUE}" && test -z "${CONFIG_RTNET_EEPRO100_F
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_EEPRO100\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTNET_EEPRO100\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTNET_PCNET32_TRUE}" && test -z "${CONFIG_RTNET_PCNET32_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_PCNET32\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTNET_PCNET32\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5739,12 +5825,16 @@ s,@RTAI_KMOD_CFLAGS@,$RTAI_KMOD_CFLAGS,;t t
 s,@RTAI_CFLAGS@,$RTAI_CFLAGS,;t t
 s,@KERNEL_CFLAGS@,$KERNEL_CFLAGS,;t t
 s,@CROSS_COMPILE@,$CROSS_COMPILE,;t t
+s,@CONFIG_RTNET_RTSKB_USE_KMALLOC_TRUE@,$CONFIG_RTNET_RTSKB_USE_KMALLOC_TRUE,;t t
+s,@CONFIG_RTNET_RTSKB_USE_KMALLOC_FALSE@,$CONFIG_RTNET_RTSKB_USE_KMALLOC_FALSE,;t t
 s,@CONFIG_RTNET_3C59X_TRUE@,$CONFIG_RTNET_3C59X_TRUE,;t t
 s,@CONFIG_RTNET_3C59X_FALSE@,$CONFIG_RTNET_3C59X_FALSE,;t t
 s,@CONFIG_RTNET_8139_TRUE@,$CONFIG_RTNET_8139_TRUE,;t t
 s,@CONFIG_RTNET_8139_FALSE@,$CONFIG_RTNET_8139_FALSE,;t t
 s,@CONFIG_RTNET_EEPRO100_TRUE@,$CONFIG_RTNET_EEPRO100_TRUE,;t t
 s,@CONFIG_RTNET_EEPRO100_FALSE@,$CONFIG_RTNET_EEPRO100_FALSE,;t t
+s,@CONFIG_RTNET_PCNET32_TRUE@,$CONFIG_RTNET_PCNET32_TRUE,;t t
+s,@CONFIG_RTNET_PCNET32_FALSE@,$CONFIG_RTNET_PCNET32_FALSE,;t t
 s,@CONFIG_RTNET_LOOPBACK_TRUE@,$CONFIG_RTNET_LOOPBACK_TRUE,;t t
 s,@CONFIG_RTNET_LOOPBACK_FALSE@,$CONFIG_RTNET_LOOPBACK_FALSE,;t t
 s,@CONFIG_RTNET_TULIP_TRUE@,$CONFIG_RTNET_TULIP_TRUE,;t t
