* added natsemi-rt driver by Erik Buit
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@311 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -470,7 +470,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS NCURSES_LIBS LIBOBJS RTAI_DIR RTNET_MODULE_DIR CONFIG_NEWLXRT_TRUE CONFIG_NEWLXRT_FALSE RTAI_KMOD_CFLAGS LXRT_CFLAGS KERNEL_CFLAGS LD CONFIG_RTNET_3C59X_TRUE CONFIG_RTNET_3C59X_FALSE CONFIG_RTNET_8139_TRUE CONFIG_RTNET_8139_FALSE CONFIG_RTNET_EEPRO100_TRUE CONFIG_RTNET_EEPRO100_FALSE CONFIG_RTNET_PCNET32_TRUE CONFIG_RTNET_PCNET32_FALSE CONFIG_RTNET_VIA_RHINE_TRUE CONFIG_RTNET_VIA_RHINE_FALSE CONFIG_RTNET_LOOPBACK_TRUE CONFIG_RTNET_LOOPBACK_FALSE CONFIG_RTNET_TULIP_TRUE CONFIG_RTNET_TULIP_FALSE CONFIG_RTNET_FCC_ENET_TRUE CONFIG_RTNET_FCC_ENET_FALSE CONFIG_RTNET_SCC_ENET_TRUE CONFIG_RTNET_SCC_ENET_FALSE CONFIG_RTNET_FEC_ENET_TRUE CONFIG_RTNET_FEC_ENET_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL CCAS CCASFLAGS NCURSES_LIBS LIBOBJS RTAI_DIR RTNET_MODULE_DIR CONFIG_NEWLXRT_TRUE CONFIG_NEWLXRT_FALSE RTAI_KMOD_CFLAGS LXRT_CFLAGS KERNEL_CFLAGS LD CONFIG_RTNET_3C59X_TRUE CONFIG_RTNET_3C59X_FALSE CONFIG_RTNET_8139_TRUE CONFIG_RTNET_8139_FALSE CONFIG_RTNET_EEPRO100_TRUE CONFIG_RTNET_EEPRO100_FALSE CONFIG_RTNET_PCNET32_TRUE CONFIG_RTNET_PCNET32_FALSE CONFIG_RTNET_VIA_RHINE_TRUE CONFIG_RTNET_VIA_RHINE_FALSE CONFIG_RTNET_NATSEMI_TRUE CONFIG_RTNET_NATSEMI_FALSE CONFIG_RTNET_LOOPBACK_TRUE CONFIG_RTNET_LOOPBACK_FALSE CONFIG_RTNET_TULIP_TRUE CONFIG_RTNET_TULIP_FALSE CONFIG_RTNET_FCC_ENET_TRUE CONFIG_RTNET_FCC_ENET_FALSE CONFIG_RTNET_SCC_ENET_TRUE CONFIG_RTNET_SCC_ENET_FALSE CONFIG_RTNET_FEC_ENET_TRUE CONFIG_RTNET_FEC_ENET_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1025,6 +1025,7 @@ Optional Features:
   --enable-eepro100      build Intel EtherExpressPro/100 driver
   --enable-pcnet32       build AMD PCnet32 driver
   --enable-via-rhine     build VIA Rhine driver
+  --enable-natsemi       build NatSemi driver
   --enable-loopback      build loopback driver
   --enable-tulip         build tulip driver
   --enable-fcc-enet      build fcc enet driver
@@ -4648,7 +4649,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4651 "configure"' > conftest.$ac_ext
+  echo '#line 4652 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5189,7 +5190,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5192: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5193: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7028,7 +7029,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7031 "configure"
+#line 7032 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7126,7 +7127,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7129 "configure"
+#line 7130 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9342,6 +9343,30 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking whether to build NatSemi driver" >&5
+echo $ECHO_N "checking whether to build NatSemi driver... $ECHO_C" >&6
+# Check whether --enable-natsemi or --disable-natsemi was given.
+if test "${enable_natsemi+set}" = set; then
+  enableval="$enable_natsemi"
+  case "$enableval" in
+	y | yes ) CONFIG_RTNET_NATSEMI=yes;;
+	*) unset CONFIG_RTNET_NATSEMI ;;
+	esac
+fi;
+echo "$as_me:$LINENO: result: ${CONFIG_RTNET_NATSEMI:-no}" >&5
+echo "${ECHO_T}${CONFIG_RTNET_NATSEMI:-no}" >&6
+
+
+if test "$CONFIG_RTNET_NATSEMI" = "yes"; then
+  CONFIG_RTNET_NATSEMI_TRUE=
+  CONFIG_RTNET_NATSEMI_FALSE='#'
+else
+  CONFIG_RTNET_NATSEMI_TRUE='#'
+  CONFIG_RTNET_NATSEMI_FALSE=
+fi
+
+
+
 echo "$as_me:$LINENO: checking whether to build loopback driver" >&5
 echo $ECHO_N "checking whether to build loopback driver... $ECHO_C" >&6
 # Check whether --enable-loopback or --disable-loopback was given.
@@ -9617,6 +9642,13 @@ if test -z "${CONFIG_RTNET_VIA_RHINE_TRUE}" && test -z "${CONFIG_RTNET_VIA_RHINE
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_VIA_RHINE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTNET_VIA_RHINE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTNET_NATSEMI_TRUE}" && test -z "${CONFIG_RTNET_NATSEMI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_NATSEMI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTNET_NATSEMI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10282,6 +10314,8 @@ s,@CONFIG_RTNET_PCNET32_TRUE@,$CONFIG_RTNET_PCNET32_TRUE,;t t
 s,@CONFIG_RTNET_PCNET32_FALSE@,$CONFIG_RTNET_PCNET32_FALSE,;t t
 s,@CONFIG_RTNET_VIA_RHINE_TRUE@,$CONFIG_RTNET_VIA_RHINE_TRUE,;t t
 s,@CONFIG_RTNET_VIA_RHINE_FALSE@,$CONFIG_RTNET_VIA_RHINE_FALSE,;t t
+s,@CONFIG_RTNET_NATSEMI_TRUE@,$CONFIG_RTNET_NATSEMI_TRUE,;t t
+s,@CONFIG_RTNET_NATSEMI_FALSE@,$CONFIG_RTNET_NATSEMI_FALSE,;t t
 s,@CONFIG_RTNET_LOOPBACK_TRUE@,$CONFIG_RTNET_LOOPBACK_TRUE,;t t
 s,@CONFIG_RTNET_LOOPBACK_FALSE@,$CONFIG_RTNET_LOOPBACK_FALSE,;t t
 s,@CONFIG_RTNET_TULIP_TRUE@,$CONFIG_RTNET_TULIP_TRUE,;t t
