* Marc's fixes of help strings
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@388 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -1038,20 +1038,20 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
-  --enable-allpci        build all PCI NIC drivers
-  --enable-3c59x         build 3Com 59x driver
-  --enable-8139          build Realtek 8139 driver
-  --enable-eepro100      build Intel EtherExpressPro/100 driver
-  --enable-pcnet32       build AMD PCnet32 driver
-  --enable-via-rhine     build VIA Rhine driver
-  --enable-natsemi       build NatSemi driver
-  --enable-tulip         build tulip driver
-  --enable-fcc-enet      build fcc enet driver
-  --enable-scc-enet      build scc enet driver
-  --enable-fec-enet      build fec enet driver
-  --enable-loopback      build loopback driver (default: enabled)
-  --enable-proxy         build IP protocol proxy driver (legacy)
-  --enable-checks        enable internal bug checks (default: enabled)
+  --enable-allpci         build all PCI NIC drivers
+  --enable-3c59x          build 3Com 59x driver
+  --enable-8139           build Realtek 8139 driver
+  --enable-eepro100       build Intel EtherExpressPro/100 driver
+  --enable-pcnet32        build AMD PCnet32 driver
+  --enable-via-rhine      build VIA Rhine driver
+  --enable-natsemi        build NatSemi driver
+  --enable-tulip          build tulip driver
+  --enable-fcc-enet       build fcc enet driver
+  --enable-scc-enet       build scc enet driver
+  --enable-fec-enet       build fec enet driver
+  --enable-loopback       build loopback driver (default: enabled)
+  --enable-proxy          build IP protocol proxy driver (legacy)
+  --enable-checks         enable internal bug checks (default: enabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1062,8 +1062,10 @@ Optional Packages:
                           both]
   --with-tags[=TAGS]
                           include additional configurations [automatic]
-  --with-rtai=RTAI    path to configured RTAI 24.1.x sources, or RTAI 3 installation
-  --with-module-dir=<module-dir>      Installation directory for modules
+  --with-rtai=RTAI        path to configured RTAI 24.1.x sources, or RTAI 3
+                          installation
+  --with-module-dir=<module-dir>
+                          Installation directory for modules
 
 Some influential environment variables:
   CC          C compiler command
@@ -1665,16 +1667,13 @@ CFLAGS=${CFLAGS:--s}
 # Check whether --with-CC or --without-CC was given.
 if test "${with_CC+set}" = set; then
   withval="$with_CC"
-
-        case "$withval" in
-        "" | y | ye | yes | n | no)
-            { { echo "$as_me:$LINENO: error: *** You must supply an argument to --with-cc." >&5
+  case "$withval" in
+    "" | y | ye | yes | n | no)
+	{ { echo "$as_me:$LINENO: error: *** You must supply an argument to --with-cc." >&5
 echo "$as_me: error: *** You must supply an argument to --with-cc." >&2;}
-   { (exit 1); exit 1; }; }
-          ;;
-        esac
-        CC="$withval"
-
+   { (exit 1); exit 1; }; } ;;
+    esac
+    CC="$withval"
 fi;
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3622,7 +3621,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3625 "configure"' > conftest.$ac_ext
+  echo '#line 3624 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5119,7 +5118,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5122:" \
+echo "$as_me:5121:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6124,11 +6123,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6127: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6126: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6131: \$? = $ac_status" >&5
+   echo "$as_me:6130: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6356,11 +6355,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6359: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6358: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6363: \$? = $ac_status" >&5
+   echo "$as_me:6362: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6423,11 +6422,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6426: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6425: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6430: \$? = $ac_status" >&5
+   echo "$as_me:6429: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8442,7 +8441,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8445 "configure"
+#line 8444 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8540,7 +8539,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8543 "configure"
+#line 8542 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10672,11 +10671,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10675: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10674: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10679: \$? = $ac_status" >&5
+   echo "$as_me:10678: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10739,11 +10738,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10742: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10741: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10746: \$? = $ac_status" >&5
+   echo "$as_me:10745: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11989,7 +11988,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11992 "configure"
+#line 11991 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12087,7 +12086,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12090 "configure"
+#line 12089 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12909,11 +12908,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12912: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12911: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12916: \$? = $ac_status" >&5
+   echo "$as_me:12915: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12976,11 +12975,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12979: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12978: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12983: \$? = $ac_status" >&5
+   echo "$as_me:12982: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14923,11 +14922,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14926: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14930: \$? = $ac_status" >&5
+   echo "$as_me:14929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15155,11 +15154,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15158: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15157: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15162: \$? = $ac_status" >&5
+   echo "$as_me:15161: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15222,11 +15221,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15225: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15224: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15229: \$? = $ac_status" >&5
+   echo "$as_me:15228: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17241,7 +17240,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17244 "configure"
+#line 17243 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17339,7 +17338,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17342 "configure"
+#line 17341 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18470,7 +18469,7 @@ fi
 
 
 
-if test "x${NCURSES_LIBS}" != "x"; then
+if test x"${NCURSES_LIBS}" != x""; then
   CONFIG_NCURSES_TRUE=
   CONFIG_NCURSES_FALSE='#'
 else
@@ -19514,15 +19513,15 @@ done
 # Check whether --with-rtai or --without-rtai was given.
 if test "${with_rtai+set}" = set; then
   withval="$with_rtai"
-
+  case "${withval}" in
+    "" | y | ye | yes | n | no)
+	{ { echo "$as_me:$LINENO: error: You must supply an argument to --with-rtai." >&5
+echo "$as_me: error: You must supply an argument to --with-rtai." >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+  with_rtai="/usr/src/rtai"
 fi;
-if test "$with_rtai" = ""; then
-   with_rtai=/usr/src/rtai
-#
-# new default value for rtai-3
-#
-#  with_rtai=/usr/realtime
-fi
 
 
 #
@@ -19899,24 +19898,16 @@ echo $ECHO_N "checking for module installation directory... $ECHO_C" >&6
 # Check whether --with-module-dir or --without-module-dir was given.
 if test "${with_module_dir+set}" = set; then
   withval="$with_module_dir"
-
-        case "$withval" in
-        "" | y | ye | yes | n | no)
-            { { echo "$as_me:$LINENO: error: You must supply an argument to --with-module-dir." >&5
+  case "${withval}" in
+    "" | y | ye | yes | n | no)
+	{ { echo "$as_me:$LINENO: error: You must supply an argument to --with-module-dir." >&5
 echo "$as_me: error: You must supply an argument to --with-module-dir." >&2;}
-   { (exit 1); exit 1; }; }
-          ;;
-        esac
-        RTNET_MODULE_DIR="$withval"
-
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+  with_module_dir='${exec_prefix}/modules'
 fi;
-
-if test "x" = "x$RTNET_MODULE_DIR"
-then
-   RTNET_MODULE_DIR='${exec_prefix}/modules'
-#  RTNET_MODULE_DIR=/lib/modules/$linux_VERSION.$linux_PATCHLEVEL.$linux_SUBLEVEL/rtnet
-fi
-
+RTNET_MODULE_DIR="$with_module_dir"
 echo "$as_me:$LINENO: result: $RTNET_MODULE_DIR" >&5
 echo "${ECHO_T}$RTNET_MODULE_DIR" >&6
 
