Support for ARP via rtnetproxy (Wolfgang Grandegger)
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@1167 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/configure b/rtnet/configure
--- a/rtnet/configure
+++ b/rtnet/configure
@@ -955,6 +955,8 @@ CONFIG_RTNET_ADDON_RTCAP_TRUE
 CONFIG_RTNET_ADDON_RTCAP_FALSE
 CONFIG_RTNET_ADDON_PROXY_TRUE
 CONFIG_RTNET_ADDON_PROXY_FALSE
+CONFIG_RTNET_ADDON_PROXY_ARP_TRUE
+CONFIG_RTNET_ADDON_PROXY_ARP_FALSE
 CONFIG_RTNET_EXAMPLES_TRUE
 CONFIG_RTNET_EXAMPLES_FALSE
 RTNET_INTERNAL_USER_CFLAGS
@@ -1612,6 +1614,8 @@ Optional Features:
   --enable-rtcap          enable RTcap support and build capturing module
                           [default=no]
   --enable-proxy          build IP protocol proxy driver (legacy) [default=no]
+  --enable-proxy-arp      enable ARP support for IP protocol proxy driver
+                          [default=no]
   --enable-examples       build examples [default=no]
   --enable-checks         enable internal bug checks [default=no]
 
@@ -4525,7 +4529,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4528 "configure"' > conftest.$ac_ext
+  echo '#line 4532 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7267,11 +7271,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7270: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7274: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7274: \$? = $ac_status" >&5
+   echo "$as_me:7278: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7557,11 +7561,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7560: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7564: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7564: \$? = $ac_status" >&5
+   echo "$as_me:7568: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7661,11 +7665,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7664: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7668: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7668: \$? = $ac_status" >&5
+   echo "$as_me:7672: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10010,7 +10014,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10013 "configure"
+#line 10017 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10110,7 +10114,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10113 "configure"
+#line 10117 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12530,11 +12534,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12533: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12537: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12537: \$? = $ac_status" >&5
+   echo "$as_me:12541: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12634,11 +12638,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12637: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12641: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12641: \$? = $ac_status" >&5
+   echo "$as_me:12645: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14196,11 +14200,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14199: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14203: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14203: \$? = $ac_status" >&5
+   echo "$as_me:14207: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14300,11 +14304,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14303: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14307: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14307: \$? = $ac_status" >&5
+   echo "$as_me:14311: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16487,11 +16491,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16490: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16494: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16494: \$? = $ac_status" >&5
+   echo "$as_me:16498: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16777,11 +16781,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16780: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16784: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16784: \$? = $ac_status" >&5
+   echo "$as_me:16788: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16881,11 +16885,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16884: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16888: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16888: \$? = $ac_status" >&5
+   echo "$as_me:16892: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21466,6 +21470,34 @@ _ACEOF
 
 fi
 
+{ echo "$as_me:$LINENO: checking whether to enable rtnetproxy ARP support" >&5
+echo $ECHO_N "checking whether to enable rtnetproxy ARP support... $ECHO_C" >&6; }
+# Check whether --enable-proxy-arp was given.
+if test "${enable_proxy_arp+set}" = set; then
+  enableval=$enable_proxy_arp; case "$enableval" in
+        y | yes) CONFIG_RTNET_ADDON_PROXY_ARP=y ;;
+        *) CONFIG_RTNET_ADDON_PROXY_ARP=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RTNET_ADDON_PROXY_ARP:-n}" >&5
+echo "${ECHO_T}${CONFIG_RTNET_ADDON_PROXY_ARP:-n}" >&6; }
+ if test "$CONFIG_RTNET_ADDON_PROXY_ARP" = "y"; then
+  CONFIG_RTNET_ADDON_PROXY_ARP_TRUE=
+  CONFIG_RTNET_ADDON_PROXY_ARP_FALSE='#'
+else
+  CONFIG_RTNET_ADDON_PROXY_ARP_TRUE='#'
+  CONFIG_RTNET_ADDON_PROXY_ARP_FALSE=
+fi
+
+if test "$CONFIG_RTNET_ADDON_PROXY_ARP" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RTNET_ADDON_PROXY_ARP 1
+_ACEOF
+
+fi
+
 
 #dnl ======================================================================
 #dnl             RTDM select (disabled until RTDM actually supports this)
@@ -21987,6 +22019,13 @@ if test -z "${CONFIG_RTNET_ADDON_PROXY_TRUE}" && test -z "${CONFIG_RTNET_ADDON_P
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_ADDON_PROXY\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RTNET_ADDON_PROXY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RTNET_ADDON_PROXY_ARP_TRUE}" && test -z "${CONFIG_RTNET_ADDON_PROXY_ARP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RTNET_ADDON_PROXY_ARP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RTNET_ADDON_PROXY_ARP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22790,6 +22829,8 @@ CONFIG_RTNET_ADDON_RTCAP_TRUE!$CONFIG_RTNET_ADDON_RTCAP_TRUE$ac_delim
 CONFIG_RTNET_ADDON_RTCAP_FALSE!$CONFIG_RTNET_ADDON_RTCAP_FALSE$ac_delim
 CONFIG_RTNET_ADDON_PROXY_TRUE!$CONFIG_RTNET_ADDON_PROXY_TRUE$ac_delim
 CONFIG_RTNET_ADDON_PROXY_FALSE!$CONFIG_RTNET_ADDON_PROXY_FALSE$ac_delim
+CONFIG_RTNET_ADDON_PROXY_ARP_TRUE!$CONFIG_RTNET_ADDON_PROXY_ARP_TRUE$ac_delim
+CONFIG_RTNET_ADDON_PROXY_ARP_FALSE!$CONFIG_RTNET_ADDON_PROXY_ARP_FALSE$ac_delim
 CONFIG_RTNET_EXAMPLES_TRUE!$CONFIG_RTNET_EXAMPLES_TRUE$ac_delim
 CONFIG_RTNET_EXAMPLES_FALSE!$CONFIG_RTNET_EXAMPLES_FALSE$ac_delim
 RTNET_INTERNAL_USER_CFLAGS!$RTNET_INTERNAL_USER_CFLAGS$ac_delim
@@ -22797,8 +22838,6 @@ RTEXT_KMOD_CFLAGS!$RTEXT_KMOD_CFLAGS$ac_delim
 RTEXT_USER_CFLAGS!$RTEXT_USER_CFLAGS$ac_delim
 XNPOSIX_USER_CFLAGS!$XNPOSIX_USER_CFLAGS$ac_delim
 XNPOSIX_USER_LDFLAGS!$XNPOSIX_USER_LDFLAGS$ac_delim
-RTEXT_LIBRARIES!$RTEXT_LIBRARIES$ac_delim
-RTFW_KMOD_CFLAGS!$RTFW_KMOD_CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -22840,12 +22879,14 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+RTEXT_LIBRARIES!$RTEXT_LIBRARIES$ac_delim
+RTFW_KMOD_CFLAGS!$RTFW_KMOD_CFLAGS$ac_delim
 RTEXT_KERNEL_DIR!$RTEXT_KERNEL_DIR$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 5; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
