* general revision, includes now all major RTnet featues
git-svn-id: https://rtnet.svn.sourceforge.net/svnroot/rtnet/trunk@436 be94bdbd-1fe7-0310-aeeb-c95d3c307607

diff --git a/rtnet/tools/rtnet b/rtnet/tools/rtnet
--- a/rtnet/tools/rtnet
+++ b/rtnet/tools/rtnet
@@ -1,160 +1,169 @@
 #!/bin/sh
 #
-# A simple script for loading/unloading RTnet and RTmac
+# script for loading/unloading RTnet, RTmac/TMDA, and RTcap
 #
+
+usage() {
+    cat << EOF
+Usage:
+    $0 [-cf <config-file>] {start|stop}
+        Start or stop station according to configuration file
+
+    $0 [-cf <config-file>] master <client_ip1> [<client_ip2> ...]
+        Start station as master for given list of clients
+
+    $0 [-cf <config-file>] capture
+        Start only passive realtime capturing
+EOF
+}
+
+init_rtnet() {
+    insmod $RTNET_MOD/rtnet.o >/dev/null || exit 1
+    insmod $RTNET_MOD/$RT_DRIVER.o $RT_DRIVER_OPTIONS >/dev/null || exit 1
+    $RTIFCONFIG rteth0 up $IPADDR $NETMASK_OPT
+
+    if [ $RT_LOOPBACK = "yes" ]; then
+        insmod $RTNET_MOD/loopback-rt.o >/dev/null || exit 1
+        $RTIFCONFIG rtlo up 127.0.0.1
+    fi
+
+    if [ $RTCAP = "yes" ]; then
+        insmod $RTNET_MOD/rtcap.o >/dev/null || exit 1
+        ifconfig rteth0 up
+        ifconfig rteth0-mac up
+    fi
+
+    insmod $RTNET_MOD/rtcfg.o >/dev/null
+    insmod $RTNET_MOD/rtmac.o >/dev/null
+    insmod $RTNET_MOD/tdma.o start_timer=0 >/dev/null
+}
+
+start_master() {
+    $RTCFG rteth0 server
+
+    STAGE_2_OPT=
+    if [ ! "$STAGE_2_SRC" = "" ]; then
+        STAGE_2_OPT="-stage2 $STAGE_2_SRC"
+    fi
+    for CLIENT in $TDMA_CLIENTS; do
+        $RTCFG rteth0 add $CLIENT $STAGE_2_OPT
+    done
+
+    echo -n "Waiting for all clients..."
+    $RTCFG rteth0 wait
+
+    echo
+    echo -n "Starting TDMA master..."
+    $RTIFCONFIG rteth0 mac master $TDMA_CYCLE
+    sleep 1
+
+    OFFSET=$TDMA_OFFSET
+    DELAY=0
+    for CLIENT in $TDMA_CLIENTS; do
+        $RTIFCONFIG rteth0 mac add $CLIENT $OFFSET
+        let OFFSET+=$TDMA_OFFSET
+        let DELAY+=5
+        sleep 3
+    done
+
+    $RTIFCONFIG rteth0 mac up
+    sleep $DELAY
+    ifconfig vnic0 up $IPADDR $NETMASK_OPT
+
+    echo
+    $RTCFG rteth0 ready
+}
+
 
 RTNETCFG=/etc/rtnet.conf
 
-# The following values are set in the configuration file:
-#  - RT_DRIVER
-#  - DEV
-#  - VNIC
-#  - NETMASK
-#  - IPADDR
-#  - ARP_PREFIX
-#  - ARP_LIST
-
-usage_rtnet() {
-	cat << EOF
-Usage:
-	$0 {start|up}
-	$0 arp
-	$0 mac ...
-	$0 proxy ...
-	$0 {stop|down}
-EOF
-}
-
-usage_rtmac() {
-	cat << EOF
-Usage:
-	On client side:
-	$0 mac client
-	(...run your application...)
-	$0 mac {down|stop}
-
-	On master side:
-	$0 mac master <cycle/us> [mtu/bytes]
-	$0 mac add <ip> [<ip> ...]
-	$0 mac up
-	$0 mac offset <ip> <offset/us>
-	(...run your applications...)
-	$0 mac {down|stop}
-EOF
-}
-
-usage_proxy() {
-	cat << EOF
-Usage:
-	$0 {start|up}
-	$0 {stop|down}
-EOF
-}
-
-if [ -r $RTNETCFG ]; then
-	. $RTNETCFG
-else
-	echo "Could not read $RTNETCFG"
-	exit 1
+if [ "$1" = "-cf" ]; then
+    RTNETCFG="$2"
+    shift 2
 fi
 
-ADD_MODULES="rtai_fifos"
+if [ -r $RTNETCFG ]; then
+    . $RTNETCFG
+else
+    echo "Could not read $RTNETCFG"
+    exit 1
+fi
+
+RTNET_MOD=$RTNET_PATH/modules
+RTIFCONFIG=$RTNET_PATH/sbin/rtifconfig
+RTCFG=$RTNET_PATH/sbin/rtcfg
+
+NETMASK_OPT=
+if [ ! "$NETMASK" = "" ]; then
+    NETMASK_OPT="netmask $NETMASK"
+fi
+
 
 case "$1" in
-    start|up)
-	modprobe $RT_DRIVER || exit 1
-	for MODULE in $ADD_MODULES; do
-	    modprobe $MODULE
-	done
+    start)
+        init_rtnet
 
-	rtifconfig $DEV up $IPADDR netmask $NETMASK
+        if [ $TDMA_MODE = "master" ]; then
+            start_master
+        else
+            echo -n "Stage 1: searching for master..."
+            $RTCFG rteth0 client
 
-	;;
+            echo
+            echo -n "Stage 2: waiting for other clients..."
+            if [ ! "$STAGE_2_DST" = "" ]; then
+                $RTCFG rteth0 announce -f $STAGE_2_DST
+                echo
+                /bin/sh -c "$STAGE_2_CMDS"
+            else
+                $RTCFG rteth0 announce
+                echo
+            fi
 
-    arp)
-	for i in $ARP_LIST; do
-	    rtifconfig $DEV route solicit $ARP_PREFIX.$i
-	done
+            $RTIFCONFIG rteth0 mac client
+            ifconfig vnic0 up $IPADDR $NETMASK_OPT
 
-	echo "*** ARP table"
-	cat /proc/rtai/arp
-	echo
-	echo "*** routing table"
-	cat /proc/rtai/route
+            echo -n "Stage 3: waiting for common setup completion..."
+            $RTCFG rteth0 ready
+            echo
+        fi
+        ;;
 
-	;;
+    stop)
+        ifconfig vnic0 down 2>/dev/null
+        ifconfig rteth0 down 2>/dev/null
+        ifconfig rteth0-mac down 2>/dev/null
 
-    stop|down)
-	rtifconfig $DEV down
-	for MODULE in $ADD_MODULES; do
-	    rmmod -r $MODULE
-	done
-	rmmod -r $RT_DRIVER
+        $RTIFCONFIG rteth0 mac down
 
-	;;
+        rmmod tdma rtmac rtcfg rtcap 2>/dev/null
 
-    mac)
-	case "$2" in
-	    master)
-		modprobe tdma
-		rtifconfig $DEV mac master $3 $4
-		ifconfig $VNIC up $IPADDR netmask $NETMASK
-		;;
+        $RTIFCONFIG rteth0 down
+        $RTIFCONFIG rtlo down 2>/dev/null
 
-	    client)
-		modprobe tdma
-		rtifconfig $DEV mac client
-		ifconfig $VNIC up $IPADDR netmask $NETMASK
-		;;
+        rmmod loopback-rt $RT_DRIVER rtnet 2>/dev/null
+        ;;
 
-	    add)
-		shift 2
-		for i in $* ; do
-			echo Add $i
-			rtifconfig $DEV mac add $i
-		done
-		;;
+    master)
+        shift
+        init_rtnet
+        TMDA_CLIENTS=$*
+        start_master
+        ;;
 
-	    up)
-		rtifconfig $DEV mac up
-		;;
+    capture)
+        insmod $RTNET_MOD/rtnet.o >/dev/null || exit 1
+        insmod $RTNET_MOD/$RT_DRIVER.o $RT_DRIVER_OPTIONS >/dev/null || exit 1
+        $RTIFCONFIG rteth0 up $IPADDR $NETMASK_OPT
 
-	    down|stop)
-		ifconfig $VNIC down
-		rtifconfig $DEV mac down
-		rmmod tdma
-		rmmod rtmac
-		;;
-
-	    offset)
-		rtifconfig $DEV mac offset $3 $4
-		;;
-
-	    *)
-		usage_rtmac
-		exit 1
-		;;
-	esac
-	;;
-
-    proxy)
-	case "$2" in
-	    up|start)
-		modprobe rtnetproxy && ifconfig rtproxy up $IPADDR
-		;;
-	    down|stop)
-		ifconfig rtproxy down
-		rmmod rtnetproxy
-		;;
-	    *)
-		usage_proxy
-		exit 1
-	esac
-	;;
+        insmod $RTNET_MOD/rtcap.o start_timer=1 >/dev/null || exit 1
+        ifconfig rteth0 up
+        ifconfig rteth0-mac up
+        ;;
 
     *)
-	usage_rtnet
-	exit 1
+        usage
+        exit 1
 esac
 
 exit 0
